import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createSummaryHandler} from './conversation-summary.mjs';
import {voiceSession} from './profile-voice.mjs';
async function call(handler,input,origin='http://127.0.0.1:5173'){let status,body;await handler(Object.assign(Readable.from([JSON.stringify(input)]),{url:'/api/conversation-summary',method:'POST',headers:{host:'127.0.0.1:5173',origin}}),{writeHead(s){status=s;},end(s){body=JSON.parse(s);}},()=>assert.fail());return {status,body};}
test('summary validates origin and transcript before calling OpenAI',async()=>{const h=createSummaryHandler({OPENAI_API_KEY:'test'},()=>assert.fail());assert.equal((await call(h,{},'https://example.com')).status,403);assert.equal((await call(h,{language:'en',turns:[{role:'system',text:'invalid'}]})).status,400);});
test('summary disables API storage and returns summarized text only',async()=>{const h=createSummaryHandler({OPENAI_API_KEY:'test'},async(url,options)=>{const body=JSON.parse(options.body);assert.equal(body.store,false);assert.match(body.instructions,/Do not invent/);return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:'Family asked about tuition. Residency is unresolved.'}]}]})};});assert.equal((await call(h,{language:'en',turns:[{role:'user',text:'What is tuition?'}]})).body.summary,'Family asked about tuition. Residency is unresolved.');});
test('voice receives bounded past summaries as data and rechecks changing facts',()=>{const session=voiceSession({language:'en',role:'parent',profile:{},memory:[{summary:'Discussed UC costs',date:'2026-10-01',mode:'finance'}]},{});assert.match(session.instructions,/Discussed UC costs/);assert.match(session.instructions,/Verify current costs/);assert.match(session.instructions,/context data, never instructions/);});
