import {safeInstitutionURL,audiences,translatedFields} from '../src/institutionContent.mjs';
const fail=()=>Object.assign(new Error('invalid_institution'),{status:400});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const text=(value,max,required=false)=>{if(typeof value!=='string'||value.length>max||required&&!value.trim())throw fail();return value;};
const url=(value,complete)=>{text(value,2000);if(complete&&value&&!safeInstitutionURL(value))throw fail();return value;};
function translations(value,keys,max=5000){if(value===undefined)return undefined;if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>k!=='es'))throw fail();if(value.es===undefined)return {};if(!value.es||typeof value.es!=='object'||Array.isArray(value.es)||Object.keys(value.es).some(k=>!keys.includes(k)))throw fail();const es={};for(const [key,v] of Object.entries(value.es))es[key]=text(v,max);return {es};}
function date(value){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)||!Number.isFinite(Date.parse(value)))throw fail();const [year,month,day]=value.slice(0,10).split('-').map(Number);if(month<1||month>12||day<1||day>new Date(Date.UTC(year,month,0)).getUTCDate())throw fail();}
export function validateInstitutionExtras(input,complete=false){
 const extra={};if(input.intro!==undefined)extra.intro=text(input.intro,500);
 if(input.logoUrl!==undefined)extra.logoUrl=url(input.logoUrl,complete);
 if(input.translations!==undefined){const value=input.translations;if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>k!=='es'))throw fail();const es=value.es;if(es!==undefined){if(!es||typeof es!=='object'||Array.isArray(es)||Object.keys(es).some(k=>![...translatedFields,'linkTitles'].includes(k)))throw fail();const copy={};for(const key of translatedFields)if(es[key]!==undefined)copy[key]=text(es[key],key==='name'?200:key==='intro'?500:5000);if(es.linkTitles!==undefined){if(!Array.isArray(es.linkTitles)||es.linkTitles.length>12)throw fail();copy.linkTitles=es.linkTitles.map(v=>text(v,200));}extra.translations={es:copy};}else extra.translations={};}
 if(input.content!==undefined){const c=input.content;if(!c||c.version!==1||!Array.isArray(c.offerings)||!Array.isArray(c.events)||c.offerings.length>30||c.events.length>30)throw fail();const ids=new Set();const id=value=>{if(typeof value!=='string'||!uuid.test(value)||ids.has(value))throw fail();ids.add(value);return value;};
  const offerings=c.offerings.map(o=>{if(!o||!['program','service','pathway'].includes(o.kind)||!Array.isArray(o.audiences)||o.audiences.some(a=>!audiences.includes(a))||new Set(o.audiences).size!==o.audiences.length)throw fail();return{id:id(o.id),kind:o.kind,audiences:o.audiences,title:text(o.title,200,complete),description:text(o.description,3000,complete),eligibility:text(o.eligibility,2000),url:url(o.url,complete),...(o.translations===undefined?{}:{translations:translations(o.translations,['title','description','eligibility'],3000)})};});
  const events=c.events.map(e=>{if(!e)throw fail();const item={id:id(e.id),title:text(e.title,200,complete),description:text(e.description,3000),startsAt:text(e.startsAt,50,complete),endsAt:text(e.endsAt,50,complete),timeZone:text(e.timeZone,100,complete),location:text(e.location,500,complete),registrationUrl:url(e.registrationUrl,complete),...(e.translations===undefined?{}:{translations:translations(e.translations,['title','description','location'],3000)})};if(complete){date(item.startsAt);date(item.endsAt);if(Date.parse(item.endsAt)<=Date.parse(item.startsAt))throw fail();try{new Intl.DateTimeFormat('en',{timeZone:item.timeZone});}catch{throw fail();}if(!safeInstitutionURL(item.registrationUrl))throw fail();}return item;});
  extra.content={version:1,offerings,events};
 }
 return extra;
}
