import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {Alert,Linking,Modal,Platform,Pressable,SafeAreaView,ScrollView,Share,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {useSession} from './Session';
import {authConfig} from './authConfig';
import {inviteMessage,inviteToken,linksRequest,type LinkResult} from './linkClient';
import type {Student} from './family';

const Context=createContext({open:(_token:string)=>{},revision:0});
export const useAccountInvites=()=>useContext(Context);
const pendingKey='origen.pending-invitation.v1';
const website=(process.env.EXPO_PUBLIC_WEB_URL||'https://origenedu.ai').replace(/\/$/,'');
function Button({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button,disabled&&{opacity:0.5}]}><Text style={styles.buttonText}>{title}</Text></Pressable>;}
export function MobileInvitations({children}:{children:ReactNode}){
 const session=useSession();const [token,setToken]=useState(''),[revision,setRevision]=useState(0),[invitation,setInvitation]=useState<LinkResult['invitation']>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[es,setEs]=useState(false);
 const t=(en:string,spanish:string)=>es?spanish:en;
 const open=(next:string)=>{const valid=inviteToken(next);if(valid){setToken(valid);setInvitation(undefined);setError('');void AsyncStorage.setItem(pendingKey,valid).catch(()=>{});}};
 const close=()=>{setToken('');setInvitation(undefined);setError('');void AsyncStorage.removeItem(pendingKey).catch(()=>{});};
 useEffect(()=>{
  let active=true;
  void (async()=>{const url=await Linking.getInitialURL();const saved=await AsyncStorage.getItem(pendingKey);if(active)open(inviteToken(url||'')||saved||'');})().catch(()=>{});
  const subscription=Linking.addEventListener('url',({url})=>open(url));
  return()=>{active=false;subscription.remove();};
 },[]);
 useEffect(()=>{
  if(!token||!session.subject)return;const controller=new AbortController();
  void Promise.resolve().then(()=>{if(controller.signal.aborted)return;setBusy(true);setError('');return linksRequest(session.getToken,authConfig.apiUrl,{action:'inspect',token},controller.signal);}).then(result=>{if(!controller.signal.aborted)setInvitation(result?.invitation);}).catch(error=>{if(!controller.signal.aborted)setError(inviteMessage(error,es));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
  return()=>controller.abort();
  // The signed-in subject changes whenever the token accessor belongs to another account.
  // eslint-disable-next-line react-hooks/exhaustive-deps
 },[token,session.subject,es]);
 return <Context.Provider value={{open,revision}}>{children}<Modal visible={!!token} animationType="slide" onRequestClose={close}><SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{t('Connect on Origen','Vincular en Origen')}</Text><Button title={es?'English':'Español'} onPress={()=>setEs(!es)}/>{invitation&&<Text style={styles.body}>{invitation.inviterName||t('A family member','Un familiar')} {t('invited you to support','te invitó a apoyar a')} {invitation.studentName} {t('as a','como')} {invitation.role==='parent'?t('parent.','padre o madre.'):t('student.','estudiante.')}</Text>}<Text style={styles.body}>{t('Both people can view and edit academic profile fields and college plans. Conversations, private notes and practical needs stay separate. Either person can unlink later.','Ambos pueden ver y editar el perfil académico y los planes universitarios. Las conversaciones, notas privadas y necesidades prácticas se mantienen separadas. Cualquiera puede desvincular las cuentas después.')}</Text>{error&&<Text accessibilityRole="alert" style={styles.body}>{error}</Text>}{!session.subject?<Button title={t('Sign in or register','Iniciar sesión o registrarse')} disabled={session.loading||busy} onPress={async()=>{setBusy(true);try{await session.login();}catch{setError(t('Sign-in requires an Origen development build and configured Auth0.','Se requiere una compilación de desarrollo de Origen y Auth0 configurado.'));}finally{setBusy(false);}}}/>:<Button title={busy?t('Checking…','Consultando…'):t('Accept and link accounts','Aceptar y vincular cuentas')} disabled={busy||!invitation||!!error} onPress={async()=>{setBusy(true);try{await linksRequest(session.getToken,authConfig.apiUrl,{action:'accept',token});close();setRevision(n=>n+1);}catch(error){setError(inviteMessage(error,es));}finally{setBusy(false);}}}/>}<Button title={t('Not now','Ahora no')} onPress={close}/></ScrollView></SafeAreaView></Modal></Context.Provider>;
}
export default function AccountLinks({students,es,onChange}:{students:Student[];es:boolean;onChange:()=>void}){
 const session=useSession();const invites=useAccountInvites();const t=(en:string,spanish:string)=>es?spanish:en;
 const [data,setData]=useState<LinkResult>({links:[],invites:[]}),[studentId,setStudentId]=useState(students[0]?.id||''),[role,setRole]=useState<'parent'|'student'>('student'),[url,setUrl]=useState(''),[paste,setPaste]=useState(''),[busy,setBusy]=useState(!!session.subject),[message,setMessage]=useState('');
 const request=(operation:Record<string,unknown>,signal?:AbortSignal)=>linksRequest(session.getToken,authConfig.apiUrl,operation,signal);
 useEffect(()=>{if(!session.subject)return;const controller=new AbortController();void request({action:'load'},controller.signal).then(result=>{if(!controller.signal.aborted)setData(result);}).catch(error=>{if(!controller.signal.aborted)setMessage(inviteMessage(error,es));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[session.subject]);
 async function act(operation:Record<string,unknown>){if(busy)return;setBusy(true);setMessage('');try{const result=await request(operation);setData(result);if(result.token)setUrl(`${website}/#invite/${result.token}`);if(operation.action==='revoke')setUrl('');if(operation.action==='unlink')onChange();}catch(error){setMessage(inviteMessage(error,es));}finally{setBusy(false);}}
 const owned=students.filter(s=>!data.links.some(l=>!l.isOwner&&l.studentId===s.id));
 return <View style={styles.section}><Text style={styles.title}>{t('Linked accounts','Cuentas vinculadas')}</Text><Text style={styles.body}>{t('Share academic profile fields and college plans. Conversations, private notes and practical needs stay separate.','Comparte el perfil académico y los planes universitarios. Las conversaciones, notas privadas y necesidades prácticas se mantienen separadas.')}</Text>{!session.subject?<Text style={styles.body}>{t('Sign in to link accounts.','Inicia sesión para vincular cuentas.')}</Text>:<>
 {owned.map(student=><Pressable key={student.id} accessibilityRole="button" accessibilityState={{selected:student.id===studentId}} style={[styles.choice,student.id===studentId&&styles.selected]} onPress={()=>{setStudentId(student.id);setUrl('');}}><Text style={styles.body}>{student.name}</Text></Pressable>)}
 {owned.length>0&&<><View style={styles.row}>{(['student','parent'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:role===value}} style={[styles.choice,role===value&&styles.selected]} onPress={()=>{setRole(value);setUrl('');}}><Text style={styles.body}>{value==='student'?t('Invite student','Invitar estudiante'):t('Invite parent','Invitar padre o madre')}</Text></Pressable>)}</View><Button title={t('Create invitation link','Crear enlace de invitación')} disabled={busy} onPress={()=>void act({action:'create',studentId:owned.some(s=>s.id===studentId)?studentId:owned[0].id,role})}/></>}
 {url&&<View style={styles.selected}><Text selectable style={styles.body}>{url}</Text><Button title={t('Share invitation','Compartir invitación')} onPress={async()=>{try{if(Platform.OS==='web'&&!navigator.share){await navigator.clipboard.writeText(url);setMessage(t('Link copied.','Enlace copiado.'));}else await Share.share({message:`${t('Connect our accounts on Origen.','Vinculemos nuestras cuentas en Origen.')} ${url}`});}catch{setMessage(t('Select and copy the link above.','Selecciona y copia el enlace de arriba.'));}}}/><Text style={styles.body}>{t('Send by text, WhatsApp or email. Expires in 7 days and works once.','Envíalo por mensaje, WhatsApp o correo. Vence en 7 días y funciona una vez.')}</Text></View>}
 {data.links.map(link=><View key={link.id} style={styles.choice}><Text style={styles.body}>{link.personName||t('Linked family member','Familiar vinculado')} · {link.studentName}</Text><Button title={t('Unlink','Desvincular')} disabled={busy} onPress={()=>Alert.alert(t('Unlink accounts?','¿Desvincular cuentas?'),t('Future changes stop syncing. Each person keeps their profile copy and private history.','Los cambios futuros dejan de sincronizarse. Cada persona conserva su copia del perfil y su historial privado.'),[{text:t('Cancel','Cancelar'),style:'cancel'},{text:t('Unlink','Desvincular'),style:'destructive',onPress:()=>void act({action:'unlink',id:link.id})}])}/></View>)}
 {data.invites.map(invite=><View key={invite.id} style={styles.choice}><Text style={styles.body}>{invite.studentName} · {t('Pending invitation','Invitación pendiente')}</Text><Button title={t('Cancel invitation','Cancelar invitación')} disabled={busy} onPress={()=>void act({action:'revoke',id:invite.id})}/></View>)}
 <Text style={styles.body}>{t('Received an invitation? Paste the link here.','¿Recibiste una invitación? Pega el enlace aquí.')}</Text><TextInput accessibilityLabel={t('Invitation link','Enlace de invitación')} style={styles.input} value={paste} onChangeText={setPaste} autoCapitalize="none" autoCorrect={false}/><Button title={t('Review invitation','Revisar invitación')} disabled={!inviteToken(paste)} onPress={()=>invites.open(paste)}/><Button title={t('Refresh linked accounts','Actualizar cuentas vinculadas')} disabled={busy} onPress={()=>{void act({action:'load'});onChange();}}/>
 </>}{message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}</View>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:'#fbf8f3'},content:{padding:24,gap:16},section:{marginTop:28,borderTopWidth:1,borderTopColor:'#e4d7ca',paddingTop:24,gap:12},title:{fontSize:24,fontWeight:'600',color:'#a4513c'},body:{fontSize:14,lineHeight:23,color:'#a4513c'},button:{padding:14,minHeight:48,borderRadius:12,backgroundColor:'#a4513c',marginVertical:5},buttonText:{color:'#f4eee4',fontSize:14,fontWeight:'600',textAlign:'center'},choice:{borderWidth:1,borderColor:'#e4d7ca',borderRadius:12,padding:12},selected:{backgroundColor:'#f4eee4',borderRadius:12,padding:12},row:{flexDirection:'row',flexWrap:'wrap',gap:10},input:{backgroundColor:'white',borderWidth:1,borderColor:'#e4d7ca',borderRadius:12,padding:14,minHeight:48,color:'#a4513c'}});
