import {useCallback,useEffect,useState} from 'react';
import {Alert,Linking,Pressable,StyleSheet,Text,View} from 'react-native';
import {useSession} from './Session';
import {authConfig} from './authConfig';

type Overview={summary:string;date:string|null;sources:{title:string;url:string}[]};
export default function ConversationHistory({studentId,es}:{studentId:string|null;es:boolean}){
 const session=useSession();const [open,setOpen]=useState(false),[result,setResult]=useState<Overview|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[deleting,setDeleting]=useState(false),[showSources,setShowSources]=useState(false);
 const t=(en:string,spanish:string)=>es?spanish:en;
 const getToken=session.getToken;
 const request=useCallback(async(path:string,body:unknown)=>{const token=await getToken();if(!token)throw new Error();const response=await fetch(`${authConfig.apiUrl.replace(/\/$/,'')}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error();return data;},[getToken]);
 useEffect(()=>{if(!open||!session.subject||deleting)return;let active=true;void Promise.resolve().then(()=>{if(!active)return null;setResult(null);setLoading(true);setError(false);return request('/api/conversation-summary',{action:'overview',studentId,language:es?'es':'en'});}).then(data=>{if(!active)return;if(typeof data.summary!=='string'||!Array.isArray(data.sources))throw new Error();if(active)setResult(data);}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[open,studentId,session.subject,es,attempt,deleting,request]);
 async function clear(){if(deleting)return;setDeleting(true);try{await request('/api/conversation-history',{action:'clear',studentId});setResult(null);}catch{Alert.alert('Origen',t('Could not delete the saved discussions. Try again.','No se pudieron eliminar las conversaciones. Intenta de nuevo.'));}finally{setDeleting(false);}}
 return <View style={styles.root}><Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={()=>setOpen(value=>!value)} style={styles.toggle}><Text style={styles.label}>{studentId===null?t('Family discussion summary','Resumen de conversaciones familiares'):t('Conversation summary','Resumen de conversaciones')}</Text><Text style={styles.label}>{open?'−':'+'}</Text></Pressable>{open&&<View style={styles.content}><Text style={styles.note}>{t('One summary of your latest saved discussions.','Un resumen de tus conversaciones guardadas más recientes.')}</Text>{loading?<Text style={styles.note}>{t('Updating your summary…','Actualizando tu resumen…')}</Text>:error?<Pressable accessibilityRole="button" onPress={()=>setAttempt(n=>n+1)}><Text style={styles.label}>{t('Could not update. Tap to retry.','No se pudo actualizar. Toca para intentar de nuevo.')}</Text></Pressable>:result?.summary?<View style={styles.entry}><Text style={styles.summary}>{result.summary}</Text>{result.date&&<Text style={styles.note}>{t('Latest discussion: ','Última conversación: ')}{new Date(result.date).toLocaleDateString()}</Text>}{result.sources.length>0&&<><Pressable accessibilityRole="button" accessibilityState={{expanded:showSources}} onPress={()=>setShowSources(value=>!value)}><Text style={styles.link}>{t('Sources discussed','Fuentes consultadas')}</Text></Pressable>{showSources&&result.sources.map(source=><Pressable key={source.url} accessibilityRole="link" onPress={()=>{if(/^https?:\/\//.test(source.url))void Linking.openURL(source.url).catch(()=>Alert.alert('Origen',t('Could not open link.','No se pudo abrir el enlace.')));}}><Text style={styles.link}>{source.title}</Text></Pressable>)}</>}<Pressable accessibilityRole="button" disabled={deleting} onPress={()=>Alert.alert(t('Delete saved discussions?','¿Eliminar conversaciones guardadas?'),t('Origen will no longer use them as context.','Origen dejará de usarlas como contexto.'),[{text:t('Cancel','Cancelar'),style:'cancel'},{text:t('Delete','Eliminar'),style:'destructive',onPress:()=>void clear()}])}><Text style={styles.link}>{deleting?t('Deleting…','Eliminando…'):t('Delete saved discussions','Eliminar conversaciones guardadas')}</Text></Pressable></View>:<Text style={styles.summary}>{t('After you talk with Origen, one summary will bring your discussions together here.','Después de hablar con Origen, un resumen reunirá aquí tus conversaciones.')}</Text>}</View>}</View>;
}
const styles=StyleSheet.create({root:{marginTop:-5,marginBottom:18,borderRadius:16,backgroundColor:'#f0f4eb'},toggle:{minHeight:48,paddingHorizontal:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{fontSize:14,fontWeight:'600',color:'#254e42'},content:{paddingHorizontal:18,paddingBottom:16},note:{fontSize:11,lineHeight:18,color:'#73806f',marginVertical:10},entry:{borderTopWidth:1,borderTopColor:'#dce3d6',paddingTop:14,marginTop:10},summary:{fontSize:14,lineHeight:25,color:'#254e42'},link:{fontSize:12,lineHeight:20,color:'#254e42',paddingVertical:10,textDecorationLine:'underline'}});
