import {useCallback,useEffect,useState} from 'react';
import {Alert,Linking,Pressable,StyleSheet,Text,View} from 'react-native';
import {useSession} from './Session';
import {authConfig} from './authConfig';

type Memory={id:string;date:string;mode:string;summary:string;sources:{title:string;url:string}[]};
export default function ConversationHistory({studentId,es}:{studentId:string;es:boolean}){
 const session=useSession();const [open,setOpen]=useState(false),[items,setItems]=useState<Memory[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[deleting,setDeleting]=useState('');
 const t=(en:string,spanish:string)=>es?spanish:en;
 const getToken=session.getToken;
 const request=useCallback(async(body:unknown)=>{const token=await getToken();if(!token)throw new Error();const response=await fetch(`${authConfig.apiUrl.replace(/\/$/,'')}/api/conversation-history`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||!Array.isArray(data.items))throw new Error();return data.items as Memory[];},[getToken]);
 useEffect(()=>{if(!open||!session.subject)return;let active=true;void Promise.resolve().then(()=>{if(active){setLoading(true);setError(false);}return request({action:'load',studentId});}).then(data=>{if(active)setItems(data.reverse());}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[open,studentId,session.subject,attempt,request]);
 async function remove(id:string){if(deleting)return;setDeleting(id);try{setItems((await request({action:'delete',id,studentId})).reverse());}catch{Alert.alert('Origen',t('Could not delete this summary. Try again.','No se pudo eliminar el resumen. Intenta de nuevo.'));}finally{setDeleting('');}}
 return <View style={styles.root}><Pressable accessibilityRole="button" accessibilityState={{expanded:open}} onPress={()=>setOpen(value=>!value)} style={styles.toggle}><Text style={styles.label}>{t('Past conversations','Conversaciones anteriores')}</Text><Text style={styles.label}>{open?'−':'+'}</Text></Pressable>{open&&<View style={styles.content}><Text style={styles.note}>{t('Summaries help Origen remember your discussions. Saved to your account.','Los resúmenes ayudan a Origen a recordar lo conversado. Se guardan en tu cuenta.')}</Text>{loading?<Text style={styles.note}>{t('Loading…','Cargando…')}</Text>:error?<Pressable accessibilityRole="button" onPress={()=>setAttempt(n=>n+1)}><Text style={styles.label}>{t('Could not load. Tap to retry.','No se pudo cargar. Toca para intentar de nuevo.')}</Text></Pressable>:items.length?items.map(item=><View key={item.id} style={styles.entry}><Text style={styles.note}>{new Date(item.date).toLocaleDateString()} · {item.mode==='finance'?t('College costs','Costos universitarios'):item.mode==='admissions'?t('Applications','Solicitudes'):t('Student profile','Perfil del estudiante')}</Text><Text style={styles.summary}>{item.summary}</Text>{item.sources.map(source=><Pressable key={source.url} accessibilityRole="link" onPress={()=>{if(/^https?:\/\//.test(source.url))void Linking.openURL(source.url).catch(()=>Alert.alert('Origen',t('Could not open link.','No se pudo abrir el enlace.')));}}><Text style={styles.link}>{source.title}</Text></Pressable>)}<Pressable accessibilityRole="button" disabled={!!deleting} onPress={()=>Alert.alert(t('Delete summary?','¿Eliminar resumen?'),t('Origen will no longer use this summary as context.','Origen dejará de usar este resumen como contexto.'),[{text:t('Cancel','Cancelar'),style:'cancel'},{text:t('Delete','Eliminar'),style:'destructive',onPress:()=>void remove(item.id)}])}><Text style={styles.link}>{deleting===item.id?t('Deleting…','Eliminando…'):t('Delete summary','Eliminar resumen')}</Text></Pressable></View>):<Text style={styles.summary}>{t('After you talk with Origen, your summaries will appear here.','Después de hablar con Origen, aquí aparecerán tus resúmenes.')}</Text>}</View>}</View>;
}
const styles=StyleSheet.create({root:{marginTop:-5,marginBottom:18,borderRadius:16,backgroundColor:'#f0f4eb'},toggle:{minHeight:48,paddingHorizontal:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},label:{fontSize:14,fontWeight:'600',color:'#254e42'},content:{paddingHorizontal:18,paddingBottom:16},note:{fontSize:11,lineHeight:18,color:'#73806f',marginBottom:10},entry:{borderTopWidth:1,borderTopColor:'#dce3d6',paddingTop:14,marginTop:10},summary:{fontSize:14,lineHeight:23,color:'#254e42'},link:{fontSize:12,lineHeight:20,color:'#254e42',paddingVertical:10,textDecorationLine:'underline'}});
