import {useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {apiFetch} from './api';
export default function AccountDataControls({t}:{t:(en:string,es:string)=>string}){
 const {user,logout,loginWithRedirect}=useAuth0();const [busy,setBusy]=useState(false),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[deleted,setDeleted]=useState(false),[reauth,setReauth]=useState(false);
 async function execute(action:'export'|'delete'){
  setBusy(true);setError('');try{
   const r=await apiFetch('/api/account-data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(action==='delete'?{confirmation:confirm}:{})})});const data=await r.json();
   if(!r.ok){if(data.error==='reauthentication_required'){setReauth(true);setConfirm('');setError(t('Sign in again, reopen Settings, and confirm account closure. Nothing has been deleted.','Inicia sesión de nuevo, abre Configuración y confirma el cierre. No se ha eliminado nada.'));return;}setError(data.error==='unlink_family_first'?t('Unlink family connections below before closing your account. Other family members keep their own copies.','Desvincula las conexiones familiares antes de cerrar tu cuenta. Los demás conservan sus propias copias.'):data.error==='institution_membership_requires_review'||data.error==='reviewer_records_require_review'?t('Institution representatives and reviewers need an account-closure review to preserve institutional ownership and records.','Los representantes y revisores necesitan una revisión del cierre para conservar la titularidad y los registros institucionales.'):t('Could not complete the request. Try again.','No se pudo completar la solicitud. Intenta de nuevo.'));return;}
   if(action==='export'){
    const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='origen-account-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
   }else{
    if(user?.sub){for(const storage of [localStorage,sessionStorage])for(const key of Object.keys(storage))if(key.startsWith(`origen.user.${user.sub}.`)||key===`origen.account.${user.sub}`)storage.removeItem(key);}
    setDeleted(true);window.dispatchEvent(new Event('origen-account-closed'));
    await logout({logoutParams:{returnTo:window.location.origin}});
   }
  }catch{setError(t('Could not complete the request. Try again.','No se pudo completar la solicitud. Intenta de nuevo.'));}finally{setBusy(false);}
 }
 return <section><h3>{t('Your data','Tus datos')}</h3><p>{t('Download your stored Origen records. Linked profiles may contain the last local academic snapshot; another family member’s private records are excluded.','Descarga tus registros de Origen. Los perfiles vinculados pueden contener la última copia académica local; se excluyen los registros privados de otros familiares.')}</p><button className="account-save" disabled={busy||deleted} onClick={()=>void execute('export')}>{t('Download my data','Descargar mis datos')}</button><p>{t('Closing removes your active Origen records and blocks this sign-in from recreating them. Other devices and downloaded files are not erased remotely. Backups expire separately. Auth0 identity deletion requires a separate provider process; a minimal hashed closure receipt remains.','Cerrar elimina tus registros activos de Origen y bloquea su recreación con este acceso. No se borran otros dispositivos ni archivos descargados. Las copias de seguridad caducan por separado. Eliminar la identidad en Auth0 requiere otro proceso; se conserva un comprobante mínimo con hash.')}</p><label>{t('Type DELETE to close your account','Escribe DELETE para cerrar tu cuenta')}<input value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={busy||deleted} autoComplete="off"/></label><button className="account-save" disabled={busy||deleted||confirm!=='DELETE'} onClick={()=>void execute('delete')}>{t('Close my Origen account','Cerrar mi cuenta de Origen')}</button>{busy&&<p role="status">{t('Working…','Procesando…')}</p>}{error&&<p role="alert">{error}</p>}{reauth&&<button className="account-save" disabled={busy} onClick={()=>void loginWithRedirect({appState:{returnTo:"#app"},authorizationParams:{max_age:0,prompt:"login"}}).catch(()=>setError(t("Sign-in could not start. Try again.","No se pudo iniciar el acceso. Intenta de nuevo.")))}>{t("Sign in again","Iniciar sesión de nuevo")}</button>}{deleted&&<p role="status">{t('Your Origen account is closed.','Tu cuenta de Origen está cerrada.')}</p>}</section>;
}
