import {useEffect,useRef,useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {Download,ChevronLeft,ChevronRight,CheckCircle2,Clock3} from 'lucide-react';
import {apiFetch} from './api';
type Institution={id:string;slug:string;name:string;status:string;verification_status:string;live:boolean;updated_at:string;page_views:string|null;link_clicks:string|null};
type Report={schemaVersion:number;classification:string;generatedAt:string;month:string;timeZone:string;minimumCount:number;page:number;pageSize:number;total:number;totals:Record<string,string>;institutions:Institution[];readiness:{research:{available:boolean;synthetic:boolean;liveResearchEnabled:boolean;checks?:{id:string;label:string;passed:boolean}[];limitations?:string[]};operational:{available:boolean;ready:boolean;gates:{id:string;valid:boolean}[]}};definitions:Record<string,string>;sources:string[]};
const number=(v:unknown)=>Number(v||0).toLocaleString();
const statuses:Record<string,string>={draft:'Draft',submitted:'Awaiting review','changes-requested':'Changes requested',published:'Published'};
const gateNames:Record<string,string>={hosting:'Hosting configuration','provider-retention':'Provider retention','restore':'Backup restoration','deletion-replay':'Deletion verification','admin-access':'Admin access','accessibility':'Accessibility review',security:'Security review','incident-ownership':'Incident ownership','pilot-commitments':'Pilot commitments'};
export default function AdminInstitutions({revision,onDenied}:{revision:number;onDenied:()=>void}){
 const {getAccessTokenSilently}=useAuth0();const [data,setData]=useState<Report>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const exportController=useRef<AbortController|null>(null),version=useRef(0);
 useEffect(()=>{if(search.trim()===query)return;const timer=setTimeout(()=>{setQuery(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search,query]);
 async function request(signal:AbortSignal){const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'institution-report',search:query,status,page}),signal});if(signal.aborted)throw new DOMException('Aborted','AbortError');if(!response.ok){if([401,403].includes(response.status))onDenied();throw new Error('Institution reporting could not load. Please try again.');}return response.json() as Promise<Report>;}
 useEffect(()=>{const controller=new AbortController();version.current++;exportController.current?.abort();setExporting(false);setExportError('');setData(undefined);setError('');void request(controller.signal).then(next=>{if(!controller.signal.aborted){if(page>1&&(page-1)*25>=next.total)setPage(Math.max(1,Math.ceil(next.total/25)));else setData(next);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();exportController.current?.abort();version.current++;};},[query,status,page,revision,retry]);
 async function download(){if(exporting)return;const current=version.current,controller=new AbortController();exportController.current=controller;setExporting(true);setExportError('');try{
  // Recheck server authorization and current suppression before every download.
  const report=await request(controller.signal);if(controller.signal.aborted||current!==version.current)return;
  const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`origen-internal-institutions-${report.month}-page-${report.page}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }catch{if(!controller.signal.aborted&&current===version.current)setExportError('Could not download the internal report. Try again.');}finally{if(current===version.current)setExporting(false);}}
 const month=data?new Date(data.month+'-01T12:00:00Z').toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:'UTC'}):'Last completed month';
 return <>
 <div className="admin-report-heading"><div><strong>{month} · UTC</strong><p>Anonymous page engagement · completed calendar month</p></div><button className="admin-refresh" disabled={!data||exporting||search.trim()!==query} onClick={()=>void download()}><Download size={16}/>{exporting?'Preparing…':'Download internal report'}</button></div>
 <div className="admin-user-filters"><label className="admin-search">Search institution name or slug<input aria-label="Search institution name or slug" type="search" maxLength={100} placeholder="Find an institution page" disabled={exporting} value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Page status<select aria-label="Institution page status" disabled={exporting} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All statuses</option>{Object.entries(statuses).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
 {exportError&&<div className="admin-error" role="alert">{exportError}</div>}
 {error?<div className="admin-error" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry institution report</button></div>:!data?<div className="admin-empty" role="status">Loading institution reporting…</div>:<>
 <div className="admin-stats admin-quality-stats">{[['pages','Institution pages'],['live_pages','Public pages'],['awaiting_review','Awaiting review'],['verified_pages','Verification complete']].map(([key,label])=><article key={key}><div className="admin-stat-heading">{label}</div><strong>{number(data.totals[key])}</strong><p>All current institution pages</p></article>)}</div>
 <p className="admin-quality-caption">Page verification confirms the publication workflow. It does not establish a research partnership or study approval.</p>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Institution page engagement</h2><p>Counts below {data.minimumCount}, including zero and missing counters, are suppressed.</p></div><span className="admin-count">{number(data.total)} results</span></div>

 {data.institutions.length?<div className="admin-table"><table><caption className="admin-sr-only">Institution engagement in {month}, UTC</caption><thead><tr><th>Institution page</th><th>Page status</th><th>Public page</th><th>Page views</th><th>Link clicks</th></tr></thead><tbody>{data.institutions.map(row=><tr key={row.id}><td><strong>{row.name||'Unnamed page'}</strong><small className="admin-status">{row.slug}</small></td><td>{statuses[row.status]||row.status}</td><td>{row.live?'Live':'Not published'}</td><td>{row.page_views===null?<span className="admin-suppressed">Suppressed</span>:number(row.page_views)}</td><td>{row.link_clicks===null?<span className="admin-suppressed">Suppressed</span>:number(row.link_clicks)}</td></tr>)}</tbody></table></div>:<div className="admin-empty"><h3>No matching institution pages</h3><p>Try another search or page status.</p></div>}
 <div className="admin-pagination"><span>{data.total?`${(page-1)*25+1}–${Math.min(page*25,data.total)} of ${number(data.total)}`:'0 results'}</span><div><button aria-label="Previous institution page" disabled={page===1||exporting} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><span>Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button aria-label="Next institution page" disabled={page*25>=data.total||exporting} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div>
 <p className="admin-funnel-note">{data.definitions.engagement} The download contains this filtered page, its definitions and readiness checks. It is for internal review.</p></section>
 <div className="admin-chart-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>Research demonstration</h2><p>Synthetic controls · live research reporting disabled</p></div><span className="admin-count">Synthetic only</span></div><p className="admin-funnel-note">No approved protocol is recorded. No real student cohorts, conversation content or research outcomes are included.</p>
 {data.readiness.research.available?<ul className="admin-report-checks">{data.readiness.research.checks?.map(check=><li key={check.id}>{check.passed?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}<span>{check.label}</span><strong>{check.passed?'Demonstrated':'Not demonstrated'}</strong></li>)}</ul>:<p className="admin-funnel-note">Synthetic control evidence is unavailable or invalid.</p>}
 <p className="admin-funnel-note">These results describe a historical synthetic exercise. They do not enable enrollment, release a dataset, or authorize model training.</p></section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Operational evidence</h2><p>Evidence register checks · not a live hosting audit</p></div></div><ul className="admin-report-checks">{data.readiness.operational.gates.map(gate=><li key={gate.id}>{gate.valid?<CheckCircle2 size={17}/>:<Clock3 size={17}/>}<span>{gateNames[gate.id]||gate.id}</span><strong>{gate.valid?'Evidence current':'Needs review'}</strong></li>)}</ul><p className="admin-funnel-note">{data.readiness.operational.available?'Missing, expired or incomplete evidence stays open for review.':'The evidence register is unavailable.'} Passing these checks does not constitute institutional approval.</p></section></div>
 <section className="admin-panel admin-report-next"><h2>Before a research partnership</h2><ol><li>Agree on the research question, eligible population and approved protocol with the institution.</li><li>Approve consent notices, recipient access, retention and withdrawal procedures.</li><li>Define study enrollment and outcome measures. Institution page visits do not establish student affiliation or academic outcomes.</li></ol></section>
 <p className="admin-quality-caption">Updated {new Date(data.generatedAt).toLocaleString()}. Sources: institution page records, anonymous monthly counters, synthetic control snapshot and operational evidence register.</p>
 </>}
 </>;
}
