import {useAuth0} from '@auth0/auth0-react';
import {useEffect,useRef,useState} from 'react';
import {Activity as ActivityIcon,ArrowDownLeft,ArrowLeft,ArrowUpRight,AudioLines,ChevronRight,Clock3,Info,LayoutDashboard,LogOut,RefreshCw,Users} from 'lucide-react';
import {apiFetch} from './api';
import './admin.css';
import AdminUsers from './AdminUsers';
import AdminVoiceQuality from './AdminVoiceQuality';
import AdminInstitutions from './AdminInstitutions';
type User={id:string;first_name:string;created_at:string;logins:string;last_login:string|null;voice_minutes:string};
type Activity={id:string;account_id:string;first_name:string;event:string;occurred_at:string;minutes:number;topic:string};
type Point={date:string;new_users:number;logins:number|null;voice_minutes:number|null;calls:number|null};
type Overview={totals:Record<string,string>;previous?:Record<string,string>;users:User[];activity:Activity[];series?:Point[];measuredSince?:string;comparisonReady?:boolean;generatedAt?:string;window?:{days:number;start:string;end:string}};
type View='overview'|'users'|'activity'|'voice'|'institutions';
const number=(value:unknown)=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:1});
const date=(value:string|null|undefined,short=false)=>value?new Date(value).toLocaleString(undefined,short?{month:'short',day:'numeric'}:{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const topics:Record<string,string>={profile:'Onboarding',finance:'College costs',admissions:'Applications',planning:'Planning',loans:'Loans'};
export function AdminLink(){const {getAccessTokenSilently}=useAuth0();const [allowed,setAllowed]=useState(false);useEffect(()=>{let active=true;void getAccessTokenSilently().then(token=>apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'access'})})).then(r=>{if(active)setAllowed(r.ok);}).catch(()=>{});return()=>{active=false;};},[]);return allowed?<a href="#admin">Admin dashboard</a>:null;}
function Comparison({current,previous,available}:{current:unknown;previous:unknown;available:boolean}){
 if(!available)return <span className="admin-comparison">Comparison available after a full tracking period</span>;
 const a=Number(current||0),b=Number(previous||0),change=a-b;
 return <span className="admin-comparison">{change>0?<ArrowUpRight size={14}/>:change<0?<ArrowDownLeft size={14}/>:null}{b===0?(a===0?'No change':`${number(change)} more`):`${change>0?'+':''}${number(change/b*100)}%`} <span>vs previous period</span></span>;
}
function Trend({points,metric,title,unit}:{points:Point[];metric:'new_users'|'voice_minutes';title:string;unit:string}){
 const [selected,setSelected]=useState<string>();
 const available=points.filter(p=>p[metric]!==null),maximum=Math.max(1,...available.map(p=>Number(p[metric])));
 const focused=points.find(p=>p.date===selected);
 const tick=(p:Point)=>new Date(p.date+'T12:00:00Z').toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'});
 return <section className="admin-panel admin-trend"><div className="admin-panel-heading"><div><h2>{title}</h2><p>Daily · UTC · {unit}</p></div>{metric==='new_users'?<Users size={20}/>:<AudioLines size={20}/>}</div>
 {!available.length?<div className="admin-empty">No tracked days in this period.</div>:<>
 <div className="admin-chart" aria-label={`${title} by day`}><div className="admin-axis"><span>{number(maximum)}</span><span>{number(maximum/2)}</span><span>0</span></div><div className="admin-bars">{points.map(p=><button type="button" key={p.date} disabled={p[metric]===null} aria-label={`${tick(p)}: ${p[metric]===null?'not tracked':number(p[metric])+' '+unit}`} aria-pressed={selected===p.date} onMouseEnter={()=>setSelected(p.date)} onFocus={()=>setSelected(p.date)} onClick={()=>setSelected(p.date)} className={p[metric]===null?'untracked':selected===p.date?'selected':''}><span style={{height:p[metric]===null?'0':`${Number(p[metric])/maximum*100}%`}}/><span className="admin-zero" hidden={p[metric]!==0}/></button>)}</div></div>
 <div className="admin-chart-dates"><span>{points[0]&&tick(points[0])}</span><span>{points.at(-1)&&tick(points.at(-1)!)}</span></div>
 <p className="admin-chart-detail" aria-live="polite">{focused?`${tick(focused)} · ${focused[metric]===null?'Tracking not yet started':number(focused[metric])+' '+unit}`:'Select a day to see its value.'}</p>
 </>}
 </section>;
}
function ActivityFeed({items}:{items:Activity[]}){return items.length?<ol className="admin-feed">{items.map(item=><li key={item.event+item.id}><span className={`admin-event-icon ${item.event==='sign_in'?'signin':''}`}>{item.event==='sign_in'?<LogOut size={16}/>:<AudioLines size={16}/>}</span><div><strong>{item.first_name||'Onboarding incomplete'}</strong><span>{item.event==='sign_in'?'Signed in':`${topics[item.topic]||item.topic||'Voice'} conversation`}</span></div><div className="admin-feed-time"><time dateTime={item.occurred_at}>{date(item.occurred_at)}</time>{item.event!=='sign_in'&&<span>{number(item.minutes)} min connected</span>}</div></li>)}</ol>:<div className="admin-empty"><ActivityIcon size={26}/><h3>No activity in this period</h3><p>Sign-ins and connected calls will appear here.</p></div>;}
export default function AdminDashboard(){
 const {getAccessTokenSilently,logout}=useAuth0();
 const [data,setData]=useState<Overview>();const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const [days,setDays]=useState(30),[view,setView]=useState<View>('overview'),[definitions,setDefinitions]=useState(false);
 const requestVersion=useRef(0),controller=useRef<AbortController|undefined>(undefined);
 async function load(period=days){const version=++requestVersion.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;setLoading(true);setError('');try{const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'overview',days:period}),signal:abort.signal});if(!response.ok){if(version===requestVersion.current&&[401,403].includes(response.status))setData(undefined);throw new Error(response.status===403?'This account does not have admin access.':'Activity could not load. Try again.');}const next=await response.json();if(version===requestVersion.current)setData(next);}catch(e){if(version===requestVersion.current&&!abort.signal.aborted)setError(e instanceof Error?e.message:'Activity could not load.');}finally{if(version===requestVersion.current)setLoading(false);}}
 useEffect(()=>{void load(days);return()=>{controller.current?.abort();requestVersion.current++;};},[days]);
 const [revision,setRevision]=useState(0);
 const currentDays=data?.window?.days||days;
 const nav=[{id:'overview' as const,label:'Overview',icon:LayoutDashboard},{id:'users' as const,label:'Users',icon:Users},{id:'activity' as const,label:'Activity',icon:ActivityIcon},{id:'voice' as const,label:'Voice quality',icon:AudioLines},{id:'institutions' as const,label:'Institutions',icon:LayoutDashboard}];
 const cards=[{label:'Registered users',key:'users',icon:Users,note:'All current app accounts'},{label:'New registrations',key:'new_users',icon:ArrowUpRight,note:'Accounts created in this period'},{label:'Users signing in',key:'active_users',icon:ActivityIcon,note:'Distinct users with a sign-in'},{label:'Connected voice minutes',key:'voice_minutes',icon:AudioLines,note:'Includes listening and pauses'}];
 return <div className="admin-workspace">
 <aside className="admin-sidebar"><a className="admin-logo" href="#" aria-label="Origen home"><span aria-hidden="true">○</span> origen<span>.</span></a><span className="admin-workspace-label">Administration</span><nav aria-label="Admin navigation">{nav.map(({id,label,icon:Icon})=><button key={id} aria-current={view===id?'page':undefined} onClick={()=>setView(id)}><Icon size={19}/>{label}{view===id&&<span className="admin-nav-dot"/>}</button>)}</nav><div className="admin-sidebar-bottom"><a href="#"><ArrowLeft size={16}/> Origen home</a><button onClick={()=>void logout({logoutParams:{returnTo:window.location.origin}}).catch(()=>setError('Could not log out. Please try again.'))}><LogOut size={16}/> Log out</button></div></aside>
 <main className="admin-dashboard"><header className="admin-header"><div><div className="admin-breadcrumb">Origen <ChevronRight size={13}/> Administration</div><h1>{view==='overview'?'Activity overview':view==='users'?'Registered users':view==='voice'?'Voice quality':view==='institutions'?'Institution reporting':'Recent activity'}</h1></div><div className="admin-header-actions"><button className="admin-icon-button" aria-expanded={definitions} aria-controls="admin-definitions" aria-label="Metric definitions" onClick={()=>setDefinitions(!definitions)}><Info size={19}/></button><button className="admin-refresh" onClick={()=>{setRevision(x=>x+1);void load();}} disabled={loading}><RefreshCw size={16} className={loading?'admin-spinning':''}/>{loading?'Refreshing…':'Refresh'}</button></div></header>
 {view!=='institutions'&&<div className="admin-toolbar"><label>Reporting period <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><span className="admin-freshness"><Clock3 size={14}/>{data?`Updated ${date(data.generatedAt)}`:'Loading activity…'}</span></div>}
 {error&&<div className="admin-error" role="alert">{error} <button onClick={()=>{setRevision(x=>x+1);void load();}}>Try again</button>{data&&<span>Showing the last successfully loaded period.</span>}</div>}
 {definitions&&<section id="admin-definitions" className="admin-panel admin-definitions"><h2>How activity is measured</h2><dl>{view==='institutions'?<><dt>Institution pages</dt><dd>All current page records. A public snapshot may remain live while a newer draft is under review.</dd><dt>Monthly engagement</dt><dd>Anonymous page-view and link-click events in the last completed UTC calendar month. Events are not unique people, student enrollment or academic outcomes.</dd><dt>Suppressed counts</dt><dd>Counts below 10, including zero and absent counters, are hidden before the report is returned.</dd><dt>Download scope</dt><dd>The current filtered directory page, up to 25 rows, plus scope, definitions and readiness results. Admin access is rechecked before downloading.</dd><dt>Research readiness</dt><dd>Historical synthetic control results and operational evidence checks. No research dataset, study approval or model-training permission is provided.</dd></>:<><dt>Registered users</dt><dd>Current PostgreSQL app accounts, including unfinished onboarding. Auth0 identities that never opened the app are excluded.</dd><dt>Sign-ins</dt><dd>Successful web sign-in returns; refreshes and silent token renewals are excluded. Native sign-ins are not yet tracked.</dd><dt>Voice minutes</dt><dd>Connected web call time, including pauses, recorded by heartbeats. Missed heartbeats can undercount usage. Calls are attributed to their starting topic; this is not provider billing.</dd><dt>Dates and comparisons</dt><dd>Rolling {currentDays}-day window ending at refresh time. Daily charts use UTC; first and last days may be partial. Voice and sign-in comparisons require a fully tracked previous period.</dd><dt>Tracking began</dt><dd>{date(data?.measuredSince)}. Historical voice and sign-in activity is not reconstructed. Registrations use account creation dates. Deleted accounts are excluded.</dd></>}</dl></section>}
 {!data&&loading&&<div className="admin-skeleton" role="status" aria-label="Loading dashboard"><div className="admin-stats">{[1,2,3,4].map(n=><div key={n}/>)}</div><div className="admin-chart-grid"><div/><div/></div></div>}
 {data&&<div className={loading?'admin-content refreshing':'admin-content'} aria-busy={loading}>
 {view==='overview'&&<><div className="admin-stats">{cards.map(({label,key,icon:Icon,note})=><article key={key}><div className="admin-stat-heading"><span>{label}</span><Icon size={18}/></div><strong>{number(data.totals[key])}</strong><p>{note}</p>{key==='users'?<span className="admin-comparison">Current total · all time</span>:<Comparison current={data.totals[key]} previous={data.previous?.[key]} available={!!data.previous&&(key==='new_users'||!!data.comparisonReady)}/>}</article>)}</div>
 <div className="admin-summary-strip"><span><strong>{number(data.totals.logins)}</strong> sign-ins</span><span><strong>{number(data.totals.calls)}</strong> voice calls</span><span>Over the selected {currentDays} days</span></div>
 <div className="admin-chart-grid"><Trend points={data.series||[]} metric="new_users" title="New registrations" unit="accounts"/><Trend points={data.series||[]} metric="voice_minutes" title="Connected voice usage" unit="minutes"/></div>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Latest activity</h2><p>Sign-ins and voice conversations</p></div><button className="admin-text-button" onClick={()=>setView('activity')}>View activity <ChevronRight size={15}/></button></div><ActivityFeed items={data.activity.slice(0,6)}/></section></>}
 {view==='users'&&<AdminUsers days={currentDays} revision={revision} onDenied={()=>{setData(undefined);setError('This account does not have admin access.');}}/>}
 {view==='voice'&&<AdminVoiceQuality days={currentDays} revision={revision} onDenied={()=>{setData(undefined);setError('This account does not have admin access.');}}/>}
 {view==='institutions'&&<AdminInstitutions revision={revision} onDenied={()=>{setData(undefined);setError('This account does not have admin access.');}}/>}
 {view==='activity'&&<section className="admin-panel"><div className="admin-panel-heading"><div><h2>Activity feed</h2><p>Latest 50 events in the selected period</p></div><span className="admin-count">{data.activity.length} events</span></div><ActivityFeed items={data.activity}/></section>}
 <footer className="admin-footer">{view==='institutions'?'Institution records and evidence snapshots':'PostgreSQL activity records'} <span>{view==='institutions'?'Internal reporting · research remains synthetic':'Connected minutes are not speaking time or billable usage.'}</span></footer>
 </div>}
 </main></div>;
}
