import {useEffect,useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {apiFetch} from './api';

type Finding={category:string;confidence:string;reason:string;topic:string;language:string;evidence:{kind:string;index:number}[]};
type Report={queueSize:number;page:number;reviewTotals:Record<string,number>;summariesChecked:number;conversations:number;transcriptsAvailable:number;savedDiscussions:number;truncated:boolean;groups:{category:string;topic:string;language:string;signals:number;conversationsFlagged:number}[];recent:{reviewId:string;revision:string;decisions:string[];topic:string;language:string;date:string;summaryReview?:{status:string};coverage:{turns:number;complete:boolean};findings:Finding[]}[]};
const labels:Record<string,string>={summary_correction:'Corrections possibly lost',summary_omission:'Important context possibly missing',summary_unsupported_claim:'Possibly unsupported summary claims',summary_commitment:'Suggestions confused with commitments',summary_uncertainty:'Uncertainty possibly lost',repeated_question:'Repeated questions',clarification_request:'Requests for clearer explanations',language_drift:'Possible language drift',possibly_unanswered:'Possibly unanswered questions',topic_transition_failure:'Topic changes failed',tool_failure:'Source checks failed',language_update_failure:'Language changes failed',reply_failure:'Replies failed',transcription_failure:'Transcription failures',connection_failure:'Connection failures'};
const topicNames:Record<string,string>={profile:'Onboarding',planning:'Planning',finance:'College costs',loans:'Loans',admissions:'Applications',unknown:'Not recorded'};
export default function AdminConversationQuality({days,revision,topic,language,onDenied}:{days:number;revision:number;topic:string;language:string;onDenied:()=>void}){
 const {getAccessTokenSilently}=useAuth0();const [report,setReport]=useState<Report>(),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const [page,setPage]=useState(0),[reviewStatus,setReviewStatus]=useState('all'),[saving,setSaving]=useState(false),[reviewError,setReviewError]=useState('');
 useEffect(()=>setPage(0),[days,topic,language,reviewStatus]);
 async function decide(row:Report['recent'][number],finding:number,status:string){setSaving(true);setReviewError('');try{const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'conversation-review',reviewId:row.reviewId,revision:row.revision,finding,status})});if(!response.ok){if([401,403].includes(response.status))onDenied();throw Error(response.status===409?'Analysis changed. Refresh and review the latest findings.':'Review could not save. Please retry.');}setRetry(n=>n+1);}catch(e){setReviewError(e instanceof Error?e.message:'Review could not save.');}finally{setSaving(false);}}
 useEffect(()=>{const controller=new AbortController();setReport(undefined);setError(false);
  void(async()=>{try{const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'conversation-quality',days,topic,language,page,reviewStatus}),signal:controller.signal});if(controller.signal.aborted)return;if(!response.ok){if([401,403].includes(response.status))onDenied();throw Error();}const data=await response.json();if(!controller.signal.aborted)setReport(data);}catch{if(!controller.signal.aborted)setError(true);}})();return()=>controller.abort();
 },[days,revision,topic,language,retry,page,reviewStatus]);
 return <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Conversation experience</h2><p>Signals from actual saved conversations · automated candidates for review</p></div></div>
 {error?<div className="admin-error" role="alert">Conversation analysis could not load. <button onClick={()=>setRetry(n=>n+1)}>Retry analysis</button></div>:!report?<div className="admin-empty" role="status">Loading conversation analysis…</div>:<>
 <dl className="admin-quality-metrics"><div><dt>Conversations analyzed</dt><dd>{report.conversations.toLocaleString()}</dd></div><div><dt>Summaries checked for fidelity</dt><dd>{(report.summariesChecked??0).toLocaleString()}</dd></div><div><dt>Saved discussions in this period</dt><dd>{report.savedDiscussions.toLocaleString()}</dd></div></dl>
 <p className="admin-quality-caption">Saved discussion count includes both languages. Older discussions have no transcript analysis. Clarification can be normal learning; these signals do not establish a defect, learning outcome or overall quality score.{report.truncated?' Showing the latest 5,000 analyses in this period.':''}</p>
 {report.groups.length?<div className="admin-table"><table><thead><tr><th>Signal</th><th>Topic</th><th>Language</th><th>Conversations flagged</th><th>Occurrences</th></tr></thead><tbody>{report.groups.map(g=><tr key={[g.category,g.topic,g.language].join(':')}><td>{labels[g.category]||g.category}</td><td>{topicNames[g.topic]||g.topic}</td><td>{g.language==='en'?'English':g.language==='es'?'Spanish':'Not recorded'}</td><td>{g.conversationsFlagged}</td><td>{g.signals}</td></tr>)}</tbody></table></div>:<div className="admin-empty">{report.conversations?'No signals detected in the analyzed conversations. This does not certify conversation quality.':'Analysis starts with new saved conversations after this update is deployed.'}</div>}
 <h3>Review queue</h3><p>Raw transcripts are not retained. Turn numbers locate the original evidence but cannot reproduce it here. Choose insufficient evidence when you cannot verify a signal.</p><label>Review status <select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)}><option value="all">All analyses</option><option value="pending">Needs review</option><option value="confirmed">Confirmed issues</option><option value="false_positive">False positives</option><option value="insufficient_evidence">Insufficient evidence</option></select></label><p>{Object.entries(report.reviewTotals??{}).map(([key,value])=>`${key.replaceAll('_',' ')}: ${value}`).join(' · ')}</p>{reviewError&&<p role="alert">{reviewError}</p>}<ol className="admin-quality-incidents">{report.recent.map((row,i)=><li key={row.date+i}><div><strong>{topicNames[row.topic]||row.topic} · {row.language==='es'?'Spanish':'English'}</strong><span>{new Date(row.date).toLocaleString()} · {row.coverage.turns} transcript turns · {row.coverage.complete?'Ended conversation':'Recovered or incomplete capture'}</span></div><p>Summary review: {row.summaryReview?.status==='checked'?'Checked; findings require review':row.summaryReview?.status==='failed'?'Unavailable after review failure':row.summaryReview?.status==='too_large'?'Not checked: capture exceeds review budget':'Not checked'}</p><details><summary>{row.findings.length} signals for review</summary>{row.findings.map((finding,j)=><p key={j}><strong>{labels[finding.category]||finding.category} · {finding.confidence} confidence</strong><br/>{finding.reason}<br/><small>Evidence: {finding.evidence.map(e=>`${e.kind} ${e.index+1}`).join(', ')}</small><br/><label>Review decision <select disabled={saving} value={row.decisions[j]} onChange={e=>void decide(row,j,e.target.value)}><option value="pending">Needs review</option><option value="confirmed">Confirmed issue</option><option value="false_positive">False positive</option><option value="insufficient_evidence">Insufficient evidence</option></select></label></p>)}</details></li>)}</ol><div><button disabled={page===0||saving} onClick={()=>setPage(n=>n-1)}>Previous</button><span> Page {page+1} · {report.queueSize} analyses </span><button disabled={(page+1)*30>=report.queueSize||saving} onClick={()=>setPage(n=>n+1)}>Next</button></div>
 <p className="admin-quality-caption">Analysis uses the transcript submitted for summarization. Summary checks compare meaning across English and Spanish, with at most one bounded model request per analysis. Unchecked summaries are not counted as successful checks. Stored findings contain no transcript text. Technical events are browser reports and may be missing. Findings are retained for 90 days and removed when the associated saved discussion or account is deleted.</p>
 </>}
 </section>;
}
