import {useAuth0} from '@auth0/auth0-react';
import {useEffect,useRef,useState} from 'react';
import {Search,X,ChevronLeft,ChevronRight} from 'lucide-react';
import {apiFetch} from './api';
import AdminOnboardingTimeline from './AdminOnboardingTimeline';
import AdminOnboardingMetrics from './AdminOnboardingMetrics';
type User={id:string;first_name:string;role:string|null;created_at:string;profile_complete:boolean;onboarding_started_at:string|null;onboarding_completed_at:string|null;logins:string;last_login:string|null;voice_minutes:string;calls?:string};
type Event={id:string;event:string;occurred_at:string;minutes:number;topic:string};
type Directory={users:User[];total:number;page:number;pageSize:number;funnel:{measured_since:string|null;registered:string;started:string;completed:string;first_conversation:string;untracked:string}};
const date=(value:string|null)=>value?new Date(value).toLocaleString(): 'Not recorded';
const number=(value:unknown)=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:1});
const topics:Record<string,string>={profile:'Onboarding',planning:'Planning',finance:'College costs',admissions:'Applications',loans:'Loans'};
export default function AdminUsers({days,revision,onDenied}:{days:number;revision:number;onDenied:()=>void}){
 const {getAccessTokenSilently}=useAuth0();
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[role,setRole]=useState('all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('registered'),[direction,setDirection]=useState('desc'),[page,setPage]=useState(1);
 const [data,setData]=useState<Directory>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selected,setSelected]=useState<string>();
 const [detail,setDetail]=useState<{user:User;activity:Event[]}>(),[detailError,setDetailError]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(search.trim()===query)return;const timer=setTimeout(()=>{setQuery(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search,query]);
 useEffect(()=>{setPage(1);},[days]);
 async function request(body:object,signal:AbortSignal){const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body),signal});if(!response.ok){if([401,403].includes(response.status))onDenied();throw new Error(response.status===404?'This account no longer exists.':'Could not load users. Please try again.');}return response.json();}
 useEffect(()=>{const abort=new AbortController();setData(undefined);setError('');void request({action:'users',days,page,search:query,role,status,sort,direction},abort.signal).then(next=>{if(!abort.signal.aborted){if(page>1&&(page-1)*25>=next.total)setPage(Math.max(1,Math.ceil(next.total/25)));else setData(next);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[days,page,query,role,status,sort,direction,revision,retry]);
 useEffect(()=>{if(!selected)return;const abort=new AbortController();setDetail(undefined);setDetailError('');void request({action:'user-detail',id:selected,days},abort.signal).then(next=>{if(!abort.signal.aborted)setDetail(next);}).catch(e=>{if(!abort.signal.aborted)setDetailError(e.message);});return()=>abort.abort();},[selected,days,revision,retry]);
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 const filter=(setter:(value:string)=>void,value:string)=>{setter(value);setPage(1);};
 const funnel=data?.funnel;
 return <>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Onboarding journey</h2><p>New accounts in the selected {days} days · recorded milestones</p></div></div>
 {funnel?<><ol className="admin-funnel">{[['registered','Registered'],['started','Opened onboarding'],['completed','Saved profile'],['first_conversation','First call after setup']].map(([key,label],i)=><li key={key}><span>{String(i+1).padStart(2,'0')} / {label}</span><strong>{number(funnel[key as keyof typeof funnel])}</strong><div className="admin-funnel-track"><span style={{width:`${Number(funnel.registered)?Number(funnel[key as keyof typeof funnel])/Number(funnel.registered)*100:0}%`}}/></div></li>)}</ol><p className="admin-funnel-note">Tracking began {date(funnel.measured_since)}. {number(funnel.untracked)} older accounts in this period are excluded. Calls during onboarding are excluded. Missing events do not establish abandonment; people may return later. Role and search filters apply to the directory below.</p></>:<p className="admin-empty">{error?'Journey unavailable.':'Loading journey…'}</p>}
 </section>
 <AdminOnboardingMetrics days={days} revision={revision} onDenied={onDenied}/>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Accounts</h2><p>All app accounts · usage over the selected {days} days</p></div>{data&&<span className="admin-count">{number(data.total)} results</span>}</div>
 <div className="admin-user-filters"><label className="admin-search"><span>Search name or user ID</span><div><Search size={16}/><input aria-label="Search name or user ID" type="search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find an account"/></div></label>
 <label>Role<select aria-label="Role" value={role} onChange={e=>filter(setRole,e.target.value)}><option value="all">All roles</option><option value="parent">Parent / guardian</option><option value="student">Student</option><option value="unknown">Not provided</option></select></label>
 <label>Profile status<select aria-label="Profile status" value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="all">All profiles</option><option value="complete">Saved</option><option value="incomplete">Incomplete</option></select></label>
 <label>Sort by<select aria-label="Sort by" value={sort} onChange={e=>filter(setSort,e.target.value)}><option value="registered">Registration</option><option value="name">Name</option><option value="last_login">Last sign-in</option><option value="logins">Sign-ins</option><option value="voice_minutes">Voice minutes</option></select></label>
 <label>Order<select aria-label="Order" value={direction} onChange={e=>filter(setDirection,e.target.value)}><option value="desc">Descending</option><option value="asc">Ascending</option></select></label></div>
 {error?<div className="admin-error" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry users</button></div>:!data?<p className="admin-empty" role="status">Loading accounts…</p>:!data.users.length?<div className="admin-empty"><h3>No matching accounts</h3><p>Try another name or adjust the filters.</p></div>:<div className="admin-table"><table><caption className="admin-sr-only">Account directory</caption><thead><tr><th>User</th><th>Role / profile</th><th>Registered</th><th>Sign-ins</th><th>Voice minutes</th><th>Last sign-in</th></tr></thead><tbody>{data.users.map(user=><tr key={user.id}><td><button className="admin-user-link" onClick={()=>setSelected(user.id)}>{user.first_name||'Name not provided'}</button><small>{user.id}</small></td><td>{user.role==='parent'?'Parent / guardian':user.role==='student'?'Student':'Not provided'}<small className="admin-status">{user.profile_complete?'Profile saved':'Incomplete'}</small></td><td>{date(user.created_at)}</td><td>{number(user.logins)}</td><td>{number(user.voice_minutes)}</td><td>{date(user.last_login)}</td></tr>)}</tbody></table></div>}
 {data&&<div className="admin-pagination"><span role="status">{data.total?`${(page-1)*25+1}–${Math.min(page*25,data.total)} of ${number(data.total)}`:'0 results'}</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>setPage(x=>x-1)}><ChevronLeft size={16}/></button><span>Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button aria-label="Next page" disabled={page*25>=data.total} onClick={()=>setPage(x=>x+1)}><ChevronRight size={16}/></button></div></div>}
 </section>
 <dialog ref={dialog} className="admin-user-dialog" aria-labelledby="admin-detail-title" onClose={()=>setSelected(undefined)} onClick={e=>{if(e.target===dialog.current){const box=dialog.current.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)setSelected(undefined);}}}>
 <header><div><p>Account details</p><h2 id="admin-detail-title">{detail?.user.first_name||'User activity'}</h2></div><button autoFocus aria-label="Close account details" onClick={()=>setSelected(undefined)}><X size={20}/></button></header>
 {detailError?<div className="admin-error" role="alert">{detailError} <button onClick={()=>setRetry(x=>x+1)}>Retry details</button></div>:!detail?<p role="status">Loading account…</p>:<><p className="admin-detail-id">{detail.user.id}</p><dl className="admin-detail-facts"><dt>Role</dt><dd>{detail.user.role||'Not provided'}</dd><dt>Registered</dt><dd>{date(detail.user.created_at)}</dd><dt>Onboarding opened</dt><dd>{date(detail.user.onboarding_started_at)}</dd><dt>Profile saved</dt><dd>{detail.user.onboarding_completed_at?date(detail.user.onboarding_completed_at):detail.user.profile_complete?'Saved · completion date unknown':'Incomplete'}</dd><dt>Last sign-in</dt><dd>{date(detail.user.last_login)}</dd></dl><div className="admin-detail-usage"><span><strong>{number(detail.user.logins)}</strong>Sign-ins</span><span><strong>{number(detail.user.calls)}</strong>Calls</span><span><strong>{number(detail.user.voice_minutes)}</strong>Connected minutes</span></div><AdminOnboardingTimeline key={detail.user.id} id={detail.user.id} days={days} revision={revision} onDenied={onDenied}/><h3>Latest activity · {days} days</h3><p className="admin-funnel-note">Latest 30 events. Topic is the guide at call start. Conversation content is not displayed.</p>{detail.activity.length?<ol className="admin-detail-events">{detail.activity.map(event=><li key={event.event+event.id}><strong>{event.event==='sign_in'?'Signed in':`${topics[event.topic]||'Voice'} call · ${number(event.minutes)} min`}</strong><time>{date(event.occurred_at)}</time></li>)}</ol>:<p>No activity in this period.</p>}</>}
 </dialog></>;
}
