import {useEffect,useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {apiFetch} from './api';
type Report={totals:Record<string,string|null>;topics:{topic:string;language:string;attempts:string;connected:string;failures:string}[];errors:{event:string;code:string;count:string}[];recent:{session_id:string;attempt_id:string;event:string;code:string|null;received_at:string}[];measuredSince:string|null;generatedAt:string};
const topics:Record<string,string>={profile:'Onboarding',planning:'Planning',finance:'College costs',admissions:'Applications',loans:'Loans'};
const events:Record<string,string>={connection_failure:'Connection failure',response_failed:'Reply failure',guide_update_failed:'Topic change failed',lookup_failure:'Source lookup failed',transcription_timeout:'Transcription timeout',spoken_language_update_failed:'Language change failed'};
const number=(v:unknown)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:1});
export default function AdminVoiceQuality({days,revision,onDenied}:{days:number;revision:number;onDenied:()=>void}){
 const {getAccessTokenSilently}=useAuth0();const [data,setData]=useState<Report>(),[error,setError]=useState(''),[retry,setRetry]=useState(0),[topic,setTopic]=useState('all'),[language,setLanguage]=useState('all');
 useEffect(()=>{const controller=new AbortController();setData(undefined);setError('');void(async()=>{try{const token=await getAccessTokenSilently();const response=await apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'voice-quality',days,topic,language}),signal:controller.signal});if(controller.signal.aborted)return;if(!response.ok){if([401,403].includes(response.status))onDenied();throw new Error('Voice quality could not load. Please try again.');}const next=await response.json();if(!controller.signal.aborted)setData(next);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Voice quality could not load.');}})();return()=>controller.abort();},[days,revision,retry,topic,language]);
 const t=data?.totals,attempts=Number(t?.attempts||0),connected=Number(t?.connected||0);
 return <>
 <div className="admin-quality-filters"><label>Starting topic<select aria-label="Starting topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="all">All topics</option>{Object.entries(topics).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Starting language<select aria-label="Starting language" value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">All languages</option><option value="en">English</option><option value="es">Spanish</option></select></label></div>
 {error?<div className="admin-error" role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry voice quality</button></div>:!data?<div className="admin-empty" role="status">Loading voice quality…</div>:<>
 <div className="admin-stats admin-quality-stats">{[{label:'Recorded start attempts',value:number(attempts),note:'Includes retries as separate attempts'},{label:'Reached a connection',value:attempts?`${number(connected/attempts*100)}%`:'—',note:`${number(connected)} of ${number(attempts)} recorded attempts`},{label:'Failed before connecting',value:number(t?.start_failures),note:'A failure event was received'},{label:'Failed after connecting',value:number(t?.call_failures),note:'Attempts with a later connection failure'}].map(card=><article key={card.label}><div className="admin-stat-heading">{card.label}</div><strong>{card.value}</strong><p>{card.note}</p></article>)}</div>
 <p className="admin-quality-caption">{number(t?.unknown)} attempts have no recorded connection or failure outcome. Missing telemetry is not a confirmed failure.</p>
 <div className="admin-chart-grid"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>Conversation continuity</h2><p>Recorded events across the selected attempts</p></div></div><dl className="admin-quality-metrics">{[['guide_changes','Topic changes completed'],['guide_failures','Topic changes failed'],['reply_failures','Replies failed'],['cancellations','Replies cancelled'],['transcription_timeouts','Transcription timeouts'],['language_failures','Language changes failed']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{number(t?.[key])}</dd></div>)}</dl><p className="admin-funnel-note">Cancellations can be normal when a user interrupts. These events do not measure audible cutoffs or volume changes.</p></section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Official source lookups</h2><p>Browser-observed lookup outcomes</p></div></div><dl className="admin-quality-metrics">{[['lookup_successes','Successful lookups'],['lookup_failures','Failed lookups'],['cache_hits','Cache hits']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{number(t?.[key])}</dd></div>)}<div><dt>Average successful lookup</dt><dd>{t?.lookup_ms===null||t?.lookup_ms===undefined?'—':`${number(Number(t.lookup_ms)/1000)} sec`}</dd></div></dl><p className="admin-funnel-note">Timing includes network and client processing. It is not a server latency or provider cost measure.</p></section></div>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Quality by topic and language</h2><p>Topic and language at the start of each attempt</p></div></div>{data.topics.length?<div className="admin-table"><table><thead><tr><th>Topic</th><th>Language</th><th>Attempts</th><th>Connected</th><th>With a failure</th></tr></thead><tbody>{data.topics.map(row=><tr key={row.topic+row.language}><td>{topics[row.topic]||'Not recorded'}</td><td>{row.language==='es'?'Spanish':row.language==='en'?'English':'Not recorded'}</td><td>{number(row.attempts)}</td><td>{number(row.connected)}</td><td>{number(row.failures)}</td></tr>)}</tbody></table></div>:<div className="admin-empty">No recorded attempts for these filters.</div>}</section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Error categories</h2><p>Event counts, not unique users or calls</p></div></div>{data.errors.length?<ul className="admin-quality-errors">{data.errors.map(row=><li key={row.event+row.code}><div><strong>{events[row.event]||row.event}</strong><span>{row.code==='unspecified'?'No code recorded':row.code}</span></div><strong>{number(row.count)}</strong></li>)}</ul>:<div className="admin-empty">No error events recorded for these filters.</div>}</section>
 <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Recent incidents</h2><p>Latest 30 events · diagnostic IDs for matching technical logs</p></div></div>{data.recent.length?<ol className="admin-quality-incidents">{data.recent.map((row,i)=><li key={row.attempt_id+row.received_at+i}><div><strong>{events[row.event]||row.event}</strong><span>{new Date(row.received_at).toLocaleString()} · {row.code||'No code recorded'}</span></div><details><summary>Diagnostic IDs</summary><p>Session: <code>{row.session_id}</code></p><p>Attempt: <code>{row.attempt_id}</code></p></details></li>)}</ol>:<div className="admin-empty">No incidents recorded for these filters.</div>}</section>
 <p className="admin-quality-caption">Tracking available since {data.measuredSince?new Date(data.measuredSince).toLocaleString():'not yet deployed'}. Browser reports are best effort; offline failures and older clients can be missing. Historical Render logs are not backfilled.</p>
 </>}
 </>;
}
