import {MessageCircle,ChevronDown,Trash2} from 'lucide-react';
import './ConversationHistory.css';
import {useAuth0} from '@auth0/auth0-react';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {useFamily} from './FamilyStore';
import {flushPendingHistory} from './pendingHistory.mjs';
export type ConversationMemory={id:string;studentId:string|null;date:string;mode:string;summary:string;sources:{title:string;url:string;checkedAt:string}[]};
type Store={items:ConversationMemory[];cloud:boolean;loading:boolean;error:boolean;reload:()=>void;add:(item:ConversationMemory)=>Promise<void>;remove:(id:string)=>Promise<void>};
const Context=createContext<Store|null>(null);
export function useConversationHistory(){const store=useContext(Context);if(!store)throw new Error('ConversationHistoryProvider is required');return store;}
export function ConversationHistoryProvider({children}:{children:ReactNode}){
 const {isAuthenticated,user,getAccessTokenSilently}=useAuth0();const family=useFamily();const cloud=isAuthenticated&&!!user?.sub;
 const key=`${cloud?`origen.user.${user!.sub}`:'camino'}.conversations.v1`;
 const read=():ConversationMemory[]=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[];}catch{return [];}};
 const pending=useRef(new Map<string,ConversationMemory>());
 const [items,setItems]=useState<ConversationMemory[]>(()=>cloud?[]:read());const [loading,setLoading]=useState(cloud),[error,setError]=useState(false),[attempt,setAttempt]=useState(0);
 async function request(path:string,body:unknown,keepalive=false){const token=await getAccessTokenSilently();const base=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');const response=await fetch(`${base}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body),keepalive});const data=await response.json() as {items:ConversationMemory[]};if(!response.ok||!Array.isArray(data.items))throw new Error('history_unavailable');return data;}
 useEffect(()=>{
  if(!cloud||family.loading||family.error)return;let active=true;setLoading(true);setError(false);
  void(async()=>{try{let data=await request('/api/conversation-history',{action:'load'});const legacy=read().filter(item=>item.studentId===null||family.students.some(student=>student.id===item.studentId)).slice(-100);if(legacy.length)data=await request('/api/conversation-history',{action:'import',items:legacy});await flushPendingHistory(pending.current,new Set(family.students.map(student=>student.id)),async item=>{data=await request('/api/conversation-history',{action:'save',item});});if(active)setItems([...data.items,...[...pending.current.values()].filter(item=>!data.items.some(saved=>saved.id===item.id))]);}catch{if(active)setError(true);}finally{if(active)setLoading(false);}})();
  return()=>{active=false;};
 },[cloud,key,family.loading,family.error,family.students.map(s=>s.id).join('|'),attempt]);
 const write=(next:ConversationMemory[])=>{localStorage.setItem(key,JSON.stringify(next));setItems(next);};
 return <Context.Provider value={{items,cloud,loading,error,reload:()=>setAttempt(n=>n+1),add:async item=>{if(cloud){pending.current.set(item.id,item);if(item.studentId===null||family.students.some(student=>student.id===item.studentId)){try{const data=await request('/api/conversation-history',{action:'save',item});pending.current.delete(item.id);setItems([...data.items,...[...pending.current.values()].filter(queued=>!data.items.some(saved=>saved.id===queued.id))]);}catch(cause){setError(true);throw cause;}}else setAttempt(n=>n+1);}else write([...read().filter(x=>x.id!==item.id),item]);},remove:async id=>{if(cloud){const data=await request('/api/conversation-history',{action:'delete',id});setItems(data.items);}else write(items.filter(x=>x.id!==id));}}}>{children}</Context.Provider>;
}
export default function ConversationHistory({studentId,mode,t}:{studentId:string|null;mode?:string;t:(a:string,b:string)=>string}){const {items,remove,cloud,loading,error:loadError,reload}=useConversationHistory();const [error,setError]=useState(false);const conversations=items.filter(x=>x.studentId===studentId&&(!mode||x.mode===mode)).reverse();return <details className="conversation-history"><summary className="history-toggle"><span className="history-icon"><MessageCircle size={17} aria-hidden="true"/></span><span className="history-label">{mode==='planning'?t('Your planning conversations','Tus conversaciones de planificación'):studentId===null?t('Family conversations','Conversaciones de familia'):t('Past conversations','Conversaciones anteriores')}</span>{conversations.length>0&&<span className="history-count">{conversations.length}</span>}<ChevronDown size={17} className="history-chevron" aria-hidden="true"/></summary><div className="history-content"><p className="small-text muted">{cloud?t('Summaries help Origen remember your discussions. Saved to your account.','Los resúmenes ayudan a Origen a recordar lo conversado. Se guardan en tu cuenta.'):t('Preview summaries stay in this browser.','Los resúmenes de ejemplo se quedan en este navegador.')}</p>{conversations.map(c=><article key={c.id} className="history-entry"><small>{new Date(c.date).toLocaleDateString()} · {c.mode==='finance'?t('College costs','Costos universitarios'):c.mode==='planning'?t('Planning','Planificación'):c.mode==='admissions'?t('Applications','Solicitudes'):t('Student profile','Perfil del estudiante')}</small><p className="history-summary">{c.summary}</p>{c.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}<button className="text-button history-delete" onClick={async()=>{setError(false);try{await remove(c.id);}catch{setError(true);}}}><Trash2 size={13} aria-hidden="true"/>{t('Delete summary','Eliminar resumen')}</button></article>)}{loading&&<p className="small-text muted">{t('Loading summaries…','Cargando resúmenes…')}</p>}{loadError&&<p role="alert">{t('History could not be loaded.','No se pudo cargar el historial.')} <button className="text-button" onClick={reload}>{t('Try again','Intentar de nuevo')}</button></p>}{!loading&&!loadError&&!conversations.length&&<div className="history-empty"><strong>{t('A little reminder of what you’ve discussed','Un recordatorio de lo que han conversado')}</strong><p>{t('After you talk with Origen, your summary will appear here.','Después de hablar con Origen, aquí aparecerá tu resumen.')}</p></div>}{error&&<p role="alert">{t('Could not delete. Try again.','No se pudo eliminar. Intenta de nuevo.')}</p>}</div></details>;}
