import { useState } from 'react';
import { ArrowLeft, AtSign, MessageCircle, Plus, Send } from 'lucide-react';
type Post={id:string;author:string;title:string;body:string;category:string;replies:{author:string;body:string}[]};
export default function DiscussionBoard({t}:{t:(en:string,es:string)=>string}) {
  const [posts,setPosts]=useState<Post[]>([]);
  const [active,setActive]=useState<string|null>(null);
  const [composing,setComposing]=useState(false);
  const [title,setTitle]=useState('');const [body,setBody]=useState('');const [reply,setReply]=useState('');
  const [category,setCategory]=useState('college');const [filter,setFilter]=useState('all');
  const [mentionTarget,setMentionTarget]=useState<'post'|'reply'|null>(null);
  const categories=[['all',t('All discussions','Todas las conversaciones')],['college',t('College pathways','Caminos universitarios')],['transfer',t('Transfer','Transferencia')],['costs',t('College costs','Costos universitarios')],['support',t('Supporting students','Apoyar a estudiantes')]];
  const members=['MariaR','AnaG','LuisM'];
  const post=posts.find(p=>p.id===active);
  const mention=(target:'post'|'reply')=><div className="mention-menu"><small>{t('Example community members','Miembros de ejemplo')}</small>{members.map(name=><button key={name} type="button" onClick={()=>{if(target==='post')setBody(p=>`${p}${p?' ':''}@${name} `);else setReply(p=>`${p}${p?' ':''}@${name} `);setMentionTarget(null);}}>@{name}</button>)}</div>;
  const renderBody=(text:string)=>text.split(/(@[\w]+)/g).map((part,i)=>part.startsWith('@')?<mark key={i}>{part}</mark>:part);
  return <div className="discussion-board"><div className="notice">{t('Local discussion-board preview. Posts, replies, and mentions are not published or sent to anyone. Family profiles and private guidance are never attached.','Vista previa local. Las publicaciones, respuestas y menciones no se envían a nadie. Los perfiles familiares y la orientación privada no se adjuntan.')}</div>
    {post?<><button className="text-button" onClick={()=>setActive(null)}><ArrowLeft size={16}/>{t('All discussions','Todas las conversaciones')}</button><article className="discussion-detail"><span className="pill">{categories.find(c=>c[0]===post.category)?.[1]}</span><h2>{post.title}</h2><small>@{post.author}</small><p>{renderBody(post.body)}</p></article><h3>{t('Replies','Respuestas')} ({post.replies.length})</h3>{post.replies.map((r,i)=><div className="forum-reply" key={i}><strong>@{r.author}</strong><p>{renderBody(r.body)}</p></div>)}<form className="forum-form" onSubmit={e=>{e.preventDefault();if(!reply.trim())return;setPosts(p=>p.map(item=>item.id===post.id?{...item,replies:[...item.replies,{author:'MariaR',body:reply.trim()}]}:item));setReply('');}}><label className="field">{t('Add to the conversation','Participa en la conversación')}<textarea required value={reply} onChange={e=>setReply(e.target.value)} maxLength={4000}/></label><div className="forum-form-actions"><button type="button" className="button outline" onClick={()=>setMentionTarget(mentionTarget==='reply'?null:'reply')}><AtSign size={16}/>{t('Mention a member','Mencionar a un miembro')}</button><button className="button primary" disabled={!reply.trim()}>{t('Add preview reply','Agregar respuesta de ejemplo')}<Send size={16}/></button></div>{mentionTarget==='reply'&&mention('reply')}</form></>:<><div className="section-heading"><h2>{t('Conversations with the community','Conversaciones con la comunidad')}</h2><button className="button primary" onClick={()=>setComposing(!composing)}><Plus size={17}/>{t('Start a discussion','Iniciar conversación')}</button></div><div className="segmented">{categories.map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>
      {composing&&<form className="forum-form" onSubmit={e=>{e.preventDefault();if(!title.trim()||!body.trim())return;const id=crypto.randomUUID();setPosts(p=>[{id,author:'MariaR',title:title.trim(),body:body.trim(),category,replies:[]},...p]);setTitle('');setBody('');setComposing(false);setActive(id);}}><label className="field">{t('Discussion title','Título')}<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={160}/></label><label className="field">{t('Topic','Tema')}<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.slice(1).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="field">{t('Your question or experience','Tu pregunta o experiencia')}<textarea required value={body} onChange={e=>setBody(e.target.value)} maxLength={4000}/></label><div className="forum-form-actions"><button type="button" className="button outline" onClick={()=>setMentionTarget(mentionTarget==='post'?null:'post')}><AtSign size={16}/>{t('Mention a member','Mencionar a un miembro')}</button><button className="button primary" disabled={!title.trim()||!body.trim()}>{t('Create preview discussion','Crear conversación de ejemplo')}</button></div>{mentionTarget==='post'&&mention('post')}</form>}
      {posts.filter(p=>filter==='all'||p.category===filter).length?posts.filter(p=>filter==='all'||p.category===filter).map(p=><button className="discussion-row" key={p.id} onClick={()=>setActive(p.id)}><MessageCircle size={22}/><span><strong>{p.title}</strong><small>@{p.author} · {categories.find(c=>c[0]===p.category)?.[1]}</small></span><span>{p.replies.length} {t('replies','respuestas')}</span></button>):<div className="empty-state"><MessageCircle size={30}/><h3>{t('Make space for a conversation.','Abre espacio para una conversación.')}</h3><p>{t('Ask about an experience, share a useful resource, or start with a question.','Pregunta sobre una experiencia, comparte un recurso o empieza con una pregunta.')}</p></div>}</>}
  </div>;
}
