import AdminDashboard from './AdminDashboard';
import {apiFetch} from './api';
import InstitutionPortal,{InstitutionPublic} from './InstitutionPortal';
import {setAPITokenProvider} from './api';
import {useAuth0} from '@auth0/auth0-react';
import {useEffect,useState} from 'react';
import App from './App';
import Landing from './Landing';
import LandingInformation from './LandingInformation';
import InviteAccept from './InviteAccept';
export default function Entry(){
 const [route,setRoute]=useState(window.location.hash);
 const [closed,setClosed]=useState(false);
 const [adminAccess,setAdminAccess]=useState<{subject:string;allowed:boolean}|null>(null);
 useEffect(()=>{const stop=()=>setClosed(true);window.addEventListener('origen-account-closed',stop);return()=>window.removeEventListener('origen-account-closed',stop);},[]);
 const {isLoading,isAuthenticated,error,user,getAccessTokenSilently}=useAuth0();
 useEffect(()=>{setAPITokenProvider(isAuthenticated?()=>getAccessTokenSilently():undefined);return()=>setAPITokenProvider(undefined);},[isAuthenticated,getAccessTokenSilently]);
 useEffect(()=>{if(!isAuthenticated)return;const id=sessionStorage.getItem('origen-login-event');if(!id)return;void apiFetch('/api/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',id})}).then(r=>{if(r.ok&&sessionStorage.getItem('origen-login-event')===id)sessionStorage.removeItem('origen-login-event');}).catch(()=>{});},[isAuthenticated,getAccessTokenSilently]);
 useEffect(()=>{if(!isAuthenticated||!user?.sub){setAdminAccess(null);return;}let current=true;const subject=user.sub;void getAccessTokenSilently().then(token=>apiFetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'access'})})).then(response=>{if(current)setAdminAccess({subject,allowed:response.ok});}).catch(()=>{if(current)setAdminAccess({subject,allowed:false});});return()=>{current=false;};},[isAuthenticated,user?.sub,getAccessTokenSilently]);
 const inside=route==='#app'||route==='#welcome'||route==='#mobile-design';
 useEffect(()=>{const update=()=>setRoute(window.location.hash);window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{if(route==='#about'||route==='#privacy'){window.scrollTo(0,0);return;}const section=document.getElementById(route.slice(1));if(section)section.scrollIntoView({block:'start'});else window.scrollTo(0,0);});return()=>cancelAnimationFrame(frame);},[route]);
 if(closed)return <main><p role="status">Your Origen account is closed. Tu cuenta de Origen está cerrada.</p><a href="/">Return to Origen / Volver a Origen</a></main>;
 if(isLoading&&(inside||route==='#admin'||route==='#institutions'||route.startsWith('#invite/')||window.location.search.includes('code=')))return <main className="application-panel"><p role="status">Loading Origen… / Cargando Origen…</p></main>;
 if(error&&window.location.search.includes('error='))return <div><p role="alert">Sign-in could not be completed. Please try again.</p><a href="/">Return to Origen</a></div>;
 if(inside&&isAuthenticated&&adminAccess?.subject!==user?.sub)return <main className="application-panel"><p role="status">Opening your account… / Abriendo tu cuenta…</p></main>;
 if(inside&&isAuthenticated&&adminAccess?.allowed)return <AdminDashboard/>;
 if(route==='#admin'&&isAuthenticated)return <AdminDashboard/>;
 if(route==='#institutions')return <InstitutionPortal key={isAuthenticated?user?.sub:'anonymous'}/>;
 if(route==='#about'||route==='#privacy')return <LandingInformation page={route==='#about'?'about':'privacy'}/>;
 if(/^#institution\/[a-z0-9-]{1,100}$/.test(route))return <InstitutionPublic key={route} slug={route.slice(13)}/>;
 if(/^#invite\/[A-Za-z0-9_-]{43}$/.test(route))return <InviteAccept token={route.slice(8)}/>;
 return inside&&isAuthenticated?<App key={user?.sub}/>:<Landing/>;
}
