import {rebaseInstitutionDraft} from './institutionDraft.mjs';
import {useEffect,useState} from 'react';
import {usePageLanguage} from './usePageLanguage';
import InstitutionMetrics,{recordInstitutionMetric} from './InstitutionMetrics';
import {useAuth0} from '@auth0/auth0-react';
import {Building2,ExternalLink,ArrowLeft,CheckCircle2} from 'lucide-react';
import './InstitutionPortal.css';
type Page={name:string;website:string;description:string;programs:string;admissions:string;financialAid:string;events:string;publicEmail:string;links:{title:string;url:string}[]};
type Institution={id:string;slug:string;status:string;verificationStatus:string;revision:number;page:Page;publishedRevision?:number;reviews?:{action:string;note:string;revision:number}[];representatives?:{first_name:string;work_email:string;job_role:string}[]};
type Result={institutions?:Institution[];submissions?:Institution[];canReview?:boolean;error?:string};
const blank:Page={name:'',website:'https://',description:'',programs:'',admissions:'',financialAid:'',events:'',publicEmail:'',links:[]};
const fields=[['description','About your institution','Acerca de tu institución'],['programs','Programs and opportunities','Programas y oportunidades'],['admissions','Admissions guidance','Orientación de ingreso'],['financialAid','Financial aid resources','Recursos de ayuda económica'],['events','Events and visits','Eventos y visitas']] as const;
const safeLink=(value:string)=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:undefined;}catch{return undefined;}};
function InstitutionContent({page,es=false,preview=false,onLink}:{page:Page;es?:boolean;preview?:boolean;onLink?:(index:number)=>void}){
 const t=(a:string,b:string)=>es?b:a;
 return <article className="institution-public-card"><span className="institution-eyebrow">{preview?t('DRAFT PREVIEW · NOT PUBLIC','VISTA DEL BORRADOR · NO PÚBLICA'):t('INSTITUTION PAGE','PÁGINA INSTITUCIONAL')}</span><h1>{page.name}</h1><p className="institution-disclosure">{t('Information provided by the institution. Publication review does not independently verify every admission requirement or promise. Confirm current requirements on the institution’s official website.','Información proporcionada por la institución. La revisión de publicación no verifica de forma independiente cada requisito o promesa. Confirma los requisitos actuales en su sitio oficial.')}</p>{safeLink(page.website)&&<a className="button primary" href={safeLink(page.website)} onClick={()=>onLink?.(-1)} target="_blank" rel="noreferrer">{t('Visit official website','Visita el sitio oficial')}<ExternalLink size={16}/></a>}{fields.map(([key,en,sp])=>page[key]&&<section key={key}><h2>{t(en,sp)}</h2><p className="institution-copy">{page[key]}</p></section>)}{page.links.length>0&&<section><h2>{t('Helpful links','Enlaces útiles')}</h2>{page.links.map((l,i)=><p key={i}>{safeLink(l.url)?<a href={safeLink(l.url)} onClick={()=>onLink?.(i)} target="_blank" rel="noreferrer">{l.title} ↗</a>:l.title}</p>)}</section>}{page.publicEmail&&<section><h2>{t('Contact the institution','Contacta a la institución')}</h2>{/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(page.publicEmail)?<a href={`mailto:${page.publicEmail}`}>{page.publicEmail}</a>:<span>{page.publicEmail}</span>}</section>}</article>;
}
export function InstitutionPublic({slug}:{slug:string}){
 const [page,setPage]=useState<Page>(),[error,setError]=useState(''),[es,setEs]=useState(localStorage.getItem('origen.language')==='es');
 usePageLanguage(es?'es':'en');
 useEffect(()=>{const controller=new AbortController();void fetch(`${(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')}/api/institutions/published/${encodeURIComponent(slug)}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(!controller.signal.aborted){setPage(data.page);recordInstitutionMetric(slug,'page_view');}}).catch(()=>{if(!controller.signal.aborted)setError('This page is not available.');});return()=>controller.abort();},[slug]);
 return <main className="institution-shell"><div className="institution-actions"><a className="institution-back" href="#">← Origen</a><button className="text-button" onClick={()=>setEs(!es)}>{es?'English':'Español'}</button></div>{error?<p role="alert">{es?'Esta página no está disponible.':error}</p>:page?<><InstitutionContent page={page} es={es} onLink={index=>recordInstitutionMetric(slug,'link_click',index)}/><p className="small-text">{es?'Contamos visitas y clics de forma agregada, sin identificadores de visitantes en estos contadores.':'We count page views and link clicks in aggregate, without visitor identifiers in these counters.'}</p></>:<p role="status">{es?'Cargando página institucional…':'Loading institution page…'}</p>}</main>;
}
export default function InstitutionPortal(){
 const {isAuthenticated,isLoading,getAccessTokenSilently,loginWithRedirect,logout}=useAuth0();
 const [es,setEs]=useState(localStorage.getItem('origen.language')==='es'),[institutions,setInstitutions]=useState<Institution[]>([]),[canReview,setCanReview]=useState(false),[submissions,setSubmissions]=useState<Institution[]>([]);
 usePageLanguage(es?'es':'en');
 const [selected,setSelected]=useState<Institution|null>(null),[editing,setEditing]=useState(false),[page,setPage]=useState<Page>(blank),[representative,setRepresentative]=useState({firstName:'',workEmail:'',jobRole:''}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(false),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({});
 const [conflict,setConflict]=useState<{latest:Institution;merged:Page;fields:string[]}|null>(null);
 const t=(a:string,b:string)=>es?b:a;
 const dirty=editing&&(JSON.stringify(page)!==JSON.stringify(selected?.page||blank)||(!selected&&Object.values(representative).some(value=>value.trim())));
 function canLeave(){return !dirty||window.confirm(t('Discard your unsaved institution edits?','Descartar los cambios institucionales sin guardar?'));}
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function request(input:unknown){const token=await getAccessTokenSilently();const response=await fetch(`${(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')}/api/institutions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(input)});const data=await response.json() as Result;if(!response.ok)throw new Error(data.error||'institutions_unavailable');return data;}
 function message(e:unknown){const code=e instanceof Error?e.message:'';return code==='reauthentication_required'?t('Sign in again before approving or changing a review. Unsaved notes will need to be entered again.','Inicia sesión de nuevo antes de aprobar o cambiar una revisión. Tendrás que volver a escribir las notas sin guardar.'):code==='institution_changed'?t('This draft changed. Reload your dashboard before editing again.','Este borrador cambió. Recarga el panel antes de volver a editar.'):code==='verification_required'?t('Verify the representative’s affiliation before publishing.','Verifica la afiliación del representante antes de publicar.'):code==='independent_review_required'?t('Another reviewer must review your institution.','Otro revisor debe revisar tu institución.'):t('Could not complete this request. Check your connection and try again.','No se pudo completar la solicitud. Revisa tu conexión e intenta de nuevo.');}
 async function load(){setBusy(true);setError('');try{const r=await request({action:'load'});setInstitutions(r.institutions||[]);if(editing&&selected){const latest=r.institutions?.find(i=>i.id===selected.id);if(latest&&latest.revision!==selected.revision){const result=rebaseInstitutionDraft(selected.page,page,latest.page);if(result.conflicts.length)setConflict({latest,merged:result.merged,fields:result.conflicts});else{setSelected(latest);setPage(result.merged);setConflict(null);setNotice(t('Draft refreshed. Your edits were preserved.','Borrador actualizado. Se conservaron tus cambios.'));}}}setCanReview(!!r.canReview);if(r.canReview)setSubmissions((await request({action:'queue'})).submissions||[]);setLoaded(true);}catch(e){setError(message(e));}finally{setBusy(false);}}
 useEffect(()=>{if(isAuthenticated)void load();},[isAuthenticated]);
 async function perform(action:string,institution=selected){if(conflict)return;setBusy(true);setError('');setNotice('');try{const r=await request(action==='register'?{action,page,representative}:action==='save'?{action,id:institution!.id,revision:institution!.revision,page}:{action,id:institution!.id,revision:institution!.revision,note:reviewNotes[institution!.id]});if(r.institutions)setInstitutions(r.institutions);if(r.submissions)setSubmissions(r.submissions);setEditing(false);setSelected(null);setConflict(null);setPreview(false);setNotice(action==='submit'?t('Submitted for affiliation and page review. Your draft is not automatically published.','Enviado para revisar la afiliación y la página. El borrador no se publica automáticamente.'):action==='publish'?t('Page published.','Página publicada.'):t('Saved.','Guardado.'));}catch(e){setError(message(e));}finally{setBusy(false);}}
 const status=(s:string)=>s==='submitted'?t('Awaiting review','Pendiente de revisión'):s==='published'?t('Published','Publicada'):s==='changes-requested'?t('Changes requested','Se requieren cambios'):t('Draft','Borrador');
 return <div className="institution-portal"><header className="institution-header"><a href="#" onClick={e=>{if(!canLeave())e.preventDefault();}} className="institution-logo">○ origen.</a><span>{t('For institutions','Para instituciones')}</span><button className="text-button" onClick={()=>setEs(!es)}>{es?'English':'Español'}</button>{isAuthenticated&&<button className="button outline" onClick={()=>{if(canLeave())void logout({logoutParams:{returnTo:window.location.origin}});}}>{t('Log out','Cerrar sesión')}</button>}</header><main className="institution-shell">
 {!isAuthenticated?<><div className="institution-welcome"><Building2 size={35}/><span className="institution-eyebrow">{t('A PLACE FOR YOUR INSTITUTION','UN ESPACIO PARA TU INSTITUCIÓN')}</span><h1>{t('Help families discover what you offer.','Ayuda a las familias a descubrir lo que ofreces.')}</h1><p>{t('Register your university, college or educational institution. Create a page with programs, admissions resources, financial aid links and events.','Registra tu universidad, colegio o institución educativa. Crea una página con programas, recursos de ingreso, ayuda económica y eventos.')}</p><button className="button primary" disabled={isLoading||busy} onClick={()=>{setError('');void loginWithRedirect({appState:{returnTo:'#institutions'},authorizationParams:{ui_locales:es?'es':'en'}}).catch(e=>setError(message(e)));}}>{t('Sign in to register your institution','Inicia sesión para registrar tu institución')}</button><p className="small-text">{t('Uses your existing Origen sign-in. Representative affiliation is reviewed separately.','Utiliza tu acceso de Origen. La afiliación del representante se revisa por separado.')}</p></div><div className="institution-process">{[[t('Register a representative','Registra un representante'),t('Tell us your role and work email.','Indica tu cargo y correo laboral.')],[t('Create a draft page','Crea un borrador'),t('Preview your information before submitting.','Revisa tu información antes de enviarla.')],[t('Review and publish','Revisar y publicar'),t('Origen checks affiliation and reviews the page before publication.','Origen verifica la afiliación y revisa la página antes de publicarla.')]].map(([title,detail],i)=><section key={title}><small>0{i+1}</small><h2>{title}</h2><p>{detail}</p></section>)}</div><p className="institution-privacy">{t('Institution pages are separate from family accounts. Registration does not provide access to student profiles or private conversations.','Las páginas institucionales están separadas de las cuentas familiares. Registrarse no otorga acceso a perfiles de estudiantes ni conversaciones privadas.')}</p></>:<>
 <div className="institution-dashboard-title"><div><span className="institution-eyebrow">{t('INSTITUTION DASHBOARD','PANEL INSTITUCIONAL')}</span><h1>{t('Your institution, in your words.','Tu institución, con tus palabras.')}</h1></div><button className="button outline" disabled={busy} onClick={()=>void load()}>{t('Refresh','Actualizar')}</button></div>
 {!editing&&<><button className="button primary" disabled={busy||!loaded} onClick={()=>{setPage({...blank,links:[]});setSelected(null);setEditing(true);setError('');setNotice('');}}>{t('Register an institution','Registrar una institución')}</button>{institutions.map(i=><article className="institution-draft-card" key={i.id}><div><h2>{i.page.name}</h2><span className="institution-status">{status(i.status)} · {t('Revision','Revisión')} {i.revision}</span></div><p>{i.verificationStatus==='verified'?t('Representative affiliation reviewed.','Afiliación del representante revisada.'):t('Affiliation verification pending. Work email alone is not proof of authorization.','Verificación de afiliación pendiente. El correo laboral por sí solo no demuestra autorización.')}</p><div className="institution-actions"><button className="button outline" disabled={busy} onClick={()=>{setSelected(i);setPage(i.page);setEditing(true);setPreview(false);setError('');}}>{t('Edit draft','Editar borrador')}</button><button className="button outline" disabled={busy||i.status==='submitted'||i.status==='published'} onClick={()=>void perform('submit',i)}>{t('Submit for review','Enviar a revisión')}</button>{i.publishedRevision&&<a className="text-button" href={`#institution/${i.slug}`}>{t('View published page','Ver página publicada')} ↗</a>}</div><InstitutionMetrics id={i.id} es={es}/>{i.reviews?.filter(r=>r.action==='request-changes').slice(0,1).map(r=><p className="institution-review-note" key={r.revision}>{t('Reviewer feedback: ','Comentarios del revisor: ')}{r.note}</p>)}{i.publishedRevision&&i.publishedRevision!==i.revision&&<p className="small-text">{t('Your last approved page remains public while these changes are reviewed.','La última página aprobada sigue pública mientras se revisan estos cambios.')}</p>}</article>)}{loaded&&!institutions.length&&<p className="institution-empty">{t('Start with a draft. Only approved pages become public.','Empieza con un borrador. Solo las páginas aprobadas se hacen públicas.')}</p>}</>}
 {editing&&<section className="institution-editor"><div className="institution-actions"><button className="text-button" onClick={()=>{if(!canLeave())return;setEditing(false);setPreview(false);setConflict(null);}}><ArrowLeft size={16}/>{t('Back to dashboard','Volver al panel')}</button><button className="button outline" onClick={()=>setPreview(!preview)}>{preview?t('Edit','Editar'):t('Preview page','Vista previa')}</button></div>{preview?<InstitutionContent page={page} es={es} preview/>:<form onSubmit={e=>{e.preventDefault();void perform(selected?'save':'register');}}><fieldset disabled={busy||!!conflict} style={{border:0,padding:0,margin:0}}>
 {!selected&&<fieldset><legend>{t('Your representative information · private','Datos del representante · privados')}</legend><label>{t('First name','Nombre')}<input required maxLength={100} autoComplete="given-name" value={representative.firstName} onChange={e=>setRepresentative({...representative,firstName:e.target.value})}/></label><label>{t('Work email','Correo laboral')}<input required type="email" maxLength={320} autoComplete="email" value={representative.workEmail} onChange={e=>setRepresentative({...representative,workEmail:e.target.value})}/></label><label>{t('Your role at the institution','Tu cargo en la institución')}<input required maxLength={200} value={representative.jobRole} onChange={e=>setRepresentative({...representative,jobRole:e.target.value})}/></label></fieldset>}
 <fieldset><legend>{t('Your institution page · public after approval','Página institucional · pública después de aprobarse')}</legend><label>{t('Institution name','Nombre de la institución')}<input required maxLength={200} value={page.name} onChange={e=>setPage({...page,name:e.target.value})}/></label><label>{t('Official website (https://)','Sitio oficial (https://)')}<input required type="url" pattern="https://.*" maxLength={2000} value={page.website} onChange={e=>setPage({...page,website:e.target.value})}/></label>{fields.map(([key,en,sp])=><label key={key}>{t(en,sp)}<textarea required={key==='description'} maxLength={5000} value={page[key]} onChange={e=>setPage({...page,[key]:e.target.value})}/></label>)}<label>{t('Public contact email (optional)','Correo público de contacto (opcional)')}<input type="email" maxLength={320} value={page.publicEmail} onChange={e=>setPage({...page,publicEmail:e.target.value})}/></label><p className="small-text">{t('Your representative’s work email stays private. Only this separate contact email appears on the public page.','El correo laboral del representante permanece privado. Solo este correo de contacto aparece en la página pública.')}</p><h3>{t('Helpful links','Enlaces útiles')}</h3>{page.links.map((l,i)=><div className="institution-link-row" key={i}><label>{t('Link title','Título del enlace')}<input required maxLength={200} value={l.title} onChange={e=>setPage({...page,links:page.links.map((x,n)=>n===i?{...x,title:e.target.value}:x)})}/></label><label>URL<input required type="url" pattern="https://.*" value={l.url} onChange={e=>setPage({...page,links:page.links.map((x,n)=>n===i?{...x,url:e.target.value}:x)})}/></label><button type="button" className="text-button" aria-label={t(`Remove link ${i+1}`,`Eliminar enlace ${i+1}`)} onClick={()=>setPage({...page,links:page.links.filter((_,n)=>n!==i)})}>{t('Remove','Quitar')}</button></div>)}<button type="button" disabled={page.links.length>=12} className="button outline" onClick={()=>setPage({...page,links:[...page.links,{title:'',url:'https://'}]})}>{t('Add a link','Agregar enlace')}</button></fieldset><button className="button primary" disabled={busy||!!conflict}>{busy?t('Saving…','Guardando…'):t('Save draft','Guardar borrador')}</button><p className="small-text">{t('Saving does not publish. Submit your draft from the dashboard when it is ready.','Guardar no publica. Envía el borrador desde el panel cuando esté listo.')}</p></fieldset></form>}</section>}
 {canReview&&!editing&&<section className="institution-review-queue"><button className="button outline" disabled={busy} onClick={()=>void loginWithRedirect({appState:{returnTo:"#institutions"},authorizationParams:{max_age:0,prompt:"login"}}).catch(e=>setError(message(e)))}>{t("Sign in again for review actions","Iniciar sesión de nuevo para revisar")}</button><h2>{t('Publication review queue','Cola de revisión de publicaciones')}</h2><p>{t('Verify affiliation independently before publishing. Record how authorization was confirmed; do not put credentials or sensitive documents in review notes.','Verifica la afiliación de forma independiente antes de publicar. Registra cómo confirmaste la autorización; no incluyas credenciales ni documentos sensibles en las notas.')}</p>{submissions.map(i=><article key={i.id} className="institution-draft-card"><h3>{i.page.name}</h3>{i.representatives?.map((r,n)=><p key={n}>{r.first_name} · {r.job_role} · {r.work_email}</p>)}<details><summary>{t('Review draft content','Revisar contenido')}</summary><InstitutionContent page={i.page} es={es} preview/></details><label>{t('Review note / requested changes','Nota de revisión / cambios solicitados')}<textarea maxLength={2000} value={reviewNotes[i.id]||''} onChange={e=>setReviewNotes({...reviewNotes,[i.id]:e.target.value})}/></label><div className="institution-actions"><button className="button outline" disabled={busy||!reviewNotes[i.id]?.trim()||i.verificationStatus==='verified'} onClick={()=>void perform('verify',i)}><CheckCircle2 size={16}/>{t('Confirm affiliation','Confirmar afiliación')}</button><button className="button primary" disabled={busy||!reviewNotes[i.id]?.trim()||i.verificationStatus!=='verified'} onClick={()=>void perform('publish',i)}>{t('Approve and publish','Aprobar y publicar')}</button><button className="button outline" disabled={busy||!reviewNotes[i.id]?.trim()} onClick={()=>void perform('request-changes',i)}>{t('Request changes','Solicitar cambios')}</button></div></article>)}{!submissions.length&&<p>{t('No pending submissions.','No hay solicitudes pendientes.')}</p>}</section>}
 </>}{conflict&&<section role="alert" className="institution-review-note"><p>{t('This draft changed in another session. Choose how to resolve the overlapping edits before saving.','Este borrador cambió en otra sesión. Elige cómo resolver los cambios antes de guardar.')}</p><div className="institution-actions"><button type="button" className="button outline" onClick={()=>{setSelected(conflict.latest);setPage(conflict.merged);setConflict(null);}}>{t('Keep my edits for conflicting fields','Conservar mis cambios en los campos en conflicto')}</button><button type="button" className="button outline" onClick={()=>{setSelected(conflict.latest);setPage(conflict.latest.page);setConflict(null);}}>{t('Use latest saved draft','Usar el borrador guardado más reciente')}</button></div></section>}{busy&&<p role="status">{t('Working…','Procesando…')}</p>}{error&&<p className="institution-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<a className="institution-back" href="#" onClick={e=>{if(!canLeave())e.preventDefault();}}>{t('Return to Origen','Volver a Origen')}</a></main></div>;
}
