import {useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {apiFetch} from './api';
import {usePageLanguage} from './usePageLanguage';
export default function InstitutionInvite({token}:{token:string}){
 const {isAuthenticated,isLoading,user,loginWithRedirect,logout}=useAuth0();
 const [es,setEs]=useState(localStorage.getItem('origen.language')==='es'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 usePageLanguage(es?'es':'en');const t=(a:string,b:string)=>es?b:a;
 async function accept(){setBusy(true);setError('');try{const response=await apiFetch('/api/institutions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'accept-invite',token})});const data=await response.json();if(!response.ok)throw new Error(data.error);sessionStorage.removeItem('origen.pending-institution-invite');window.location.hash='#institutions';}catch(e){const code=e instanceof Error?e.message:'';setError(code==='invitation_email_required'?t('Use the verified email account this invitation was created for. If needed, log out and sign in with that account.','Usa la cuenta con el correo verificado para el que se creó esta invitación. Si es necesario, cierra sesión e inicia con esa cuenta.'):code==='invitation_unavailable'?t('This invitation has expired, was revoked, or has already been used. Ask the owner for a new link.','Esta invitación venció, fue revocada o ya se usó. Pide un enlace nuevo al propietario.'):code==='already_a_member'?t('You already have access. Open your institutional workspace.','Ya tienes acceso. Abre tu espacio institucional.'):t('Could not accept the invitation. Try again.','No se pudo aceptar la invitación. Intenta de nuevo.'));}finally{setBusy(false);}}
 return <main className="institution-shell"><div className="institution-actions"><a href="#">○ origen.</a><button className="text-button" onClick={()=>setEs(!es)}>{es?'English':'Español'}</button></div><section className="institution-public-card"><h1>{t('Join your institutional team','Únete a tu equipo institucional')}</h1><p>{t('Sign in using the email your coworker invited. Accepting adds access to that institutional workspace.','Inicia sesión con el correo que invitó tu colega. Al aceptar obtendrás acceso a ese espacio institucional.')}</p>{isAuthenticated?<><p>{user?.email}</p><div className="institution-actions"><button className="button primary" disabled={busy} onClick={()=>void accept()}>{busy?t('Accepting…','Aceptando…'):t('Accept invitation','Aceptar invitación')}</button><button className="button outline" disabled={busy} onClick={()=>{sessionStorage.setItem('origen.pending-institution-invite',token);void logout({logoutParams:{returnTo:window.location.origin}});}}>{t('Log out','Cerrar sesión')}</button><a href="#institutions">{t('Open institution workspace','Abrir espacio institucional')}</a></div></>:<button className="button primary" disabled={isLoading||busy} onClick={()=>{setBusy(true);void loginWithRedirect({appState:{returnTo:`#institution-invite/${token}`},authorizationParams:{ui_locales:es?'es':'en',scope:'openid profile email'}}).catch(()=>{setError(t('Could not open sign-in. Try again.','No se pudo abrir el inicio de sesión. Intenta de nuevo.'));setBusy(false);});}}>{t('Sign in or create an account','Inicia sesión o crea una cuenta')}</button>}{error&&<p role="alert">{error}</p>}</section></main>;
}
