import type {InstitutionPage,Offering,InstitutionEvent} from './institutionContent.mjs';
export default function InstitutionContentEditor({page,onChange,es,language}:{page:InstitutionPage;onChange:(page:InstitutionPage)=>void;es:boolean;language:'en'|'es'}){
 const t=(a:string,b:string)=>es?b:a,spanish=language==='es',content=page.content||{version:1 as const,offerings:[],events:[]};
 const intro=spanish?page.translations?.es?.intro||'':page.intro||'';
 function changeIntro(value:string){onChange(spanish?{...page,translations:{es:{...page.translations?.es,intro:value}}}:{...page,intro:value});}
 function changeOffering(index:number,key:string,value:unknown){const offerings=content.offerings.map((item,n)=>{if(n!==index)return item;if(spanish&&['title','description','eligibility'].includes(key))return{...item,translations:{es:{...item.translations?.es,[key]:value}}};return{...item,[key]:value};});onChange({...page,content:{...content,offerings}});}
 function changeEvent(index:number,key:string,value:string){const events=content.events.map((item,n)=>{if(n!==index)return item;if(spanish&&['title','description','location'].includes(key))return{...item,translations:{es:{...item.translations?.es,[key]:value}}};return{...item,[key]:value};});onChange({...page,content:{...content,events}});}
 const offeringText=(o:Offering,key:'title'|'description'|'eligibility')=>spanish?o.translations?.es?.[key]||'':o[key];
 const eventText=(e:InstitutionEvent,key:'title'|'description'|'location')=>spanish?e.translations?.es?.[key]||'':e[key];
 return <>
 <div data-editor-section="basics"><label>{t('Short introduction','Introducción breve')}<textarea maxLength={500} value={intro} onChange={e=>changeIntro(e.target.value)}/></label><label>{t('Institution logo URL (HTTPS, optional)','URL del logotipo (HTTPS, opcional)')}<input maxLength={2000} value={page.logoUrl||''} onChange={e=>onChange({...page,logoUrl:e.target.value})}/></label><p className="small-text">{t('Use a publicly accessible image owned by your institution. The same logo appears in both languages.','Usa una imagen pública de tu institución. El mismo logotipo aparece en ambos idiomas.')}</p></div>
 <div data-editor-section="programs" className="institution-structured-editor"><h3>{t('Structured programs, services and admissions pathways','Programas, servicios y rutas de ingreso')}</h3><p>{t('These cards help first-time students, transfer students, adult learners and families find the right action. English and Spanish versions share one record.','Estas tarjetas ayudan a estudiantes de primer ingreso, de transferencia, adultos y familias a encontrar su siguiente paso. Las versiones en inglés y español comparten un registro.')}</p>
 {content.offerings.map((item,index)=><fieldset key={item.id}><legend>{t(`Offering ${index+1}`,`Oportunidad ${index+1}`)}</legend><label>{t('Offering type','Tipo de oportunidad')}<select aria-label={t('Offering type','Tipo de oportunidad')} value={item.kind} onChange={e=>changeOffering(index,'kind',e.target.value)}><option value="program">{t('Program','Programa')}</option><option value="service">{t('Service','Servicio')}</option><option value="pathway">{t('Admissions pathway','Ruta de ingreso')}</option></select></label><label>{t('Offering title','Título de la oportunidad')}<input maxLength={200} value={offeringText(item,'title')} onChange={e=>changeOffering(index,'title',e.target.value)}/></label><label>{t('Offering description','Descripción de la oportunidad')}<textarea maxLength={3000} value={offeringText(item,'description')} onChange={e=>changeOffering(index,'description',e.target.value)}/></label><label>{t('Eligibility (optional)','Elegibilidad (opcional)')}<textarea maxLength={2000} value={offeringText(item,'eligibility')} onChange={e=>changeOffering(index,'eligibility',e.target.value)}/></label><label>{t('Official offering URL (optional)','URL oficial de la oportunidad (opcional)')}<input maxLength={2000} value={item.url} onChange={e=>changeOffering(index,'url',e.target.value)}/></label><fieldset className="institution-audiences"><legend>{t('Who this is for','Para quién es')}</legend>{[['first-year','First-time students','Estudiantes de primer ingreso'],['transfer','Transfer students','Estudiantes de transferencia'],['adult','Adult learners','Estudiantes adultos'],['family','Families','Familias']].map(([value,en,sp])=><label key={value}><input type="checkbox" checked={item.audiences.includes(value)} onChange={e=>changeOffering(index,'audiences',e.target.checked?[...item.audiences,value]:item.audiences.filter(a=>a!==value))}/>{t(en,sp)}</label>)}</fieldset><button type="button" className="text-button" onClick={()=>onChange({...page,content:{...content,offerings:content.offerings.filter((_,n)=>n!==index)}})}>{t(`Remove offering ${index+1}`,`Quitar oportunidad ${index+1}`)}</button></fieldset>)}
 <button type="button" className="button outline" disabled={content.offerings.length>=30} onClick={()=>onChange({...page,content:{...content,offerings:[...content.offerings,{id:crypto.randomUUID(),kind:'program',audiences:[],title:'',description:'',eligibility:'',url:''}]}})}>{t('Add an offering','Agregar oportunidad')}</button>
 <h3>{t('Scheduled events','Eventos programados')}</h3><p className="small-text">{t('Enter dates with an explicit UTC offset, for example 2026-11-15T17:00:00-08:00. The display timezone must match the institution’s event. Ended events are removed from upcoming listings. Registration stays on your official website.','Ingresa fechas con una diferencia UTC explícita, por ejemplo 2026-11-15T17:00:00-08:00. La zona horaria debe corresponder al evento. Los eventos terminados no aparecen como próximos. El registro permanece en tu sitio oficial.')}</p>
 {content.events.map((item,index)=><fieldset key={item.id}><legend>{t(`Event ${index+1}`,`Evento ${index+1}`)}</legend><label>{t('Event title','Título del evento')}<input maxLength={200} value={eventText(item,'title')} onChange={e=>changeEvent(index,'title',e.target.value)}/></label><label>{t('Event description','Descripción del evento')}<textarea maxLength={3000} value={eventText(item,'description')} onChange={e=>changeEvent(index,'description',e.target.value)}/></label>{[['startsAt','Start (ISO date with UTC offset)','Inicio (fecha ISO con diferencia UTC)'],['endsAt','End (ISO date with UTC offset)','Fin (fecha ISO con diferencia UTC)'],['timeZone','Display timezone (IANA)','Zona horaria (IANA)']].map(([key,en,sp])=><label key={key}>{t(en,sp)}<input maxLength={key==='timeZone'?100:50} placeholder={key==='timeZone'?'America/Los_Angeles':'2026-11-15T17:00:00-08:00'} value={item[key as 'startsAt'|'endsAt'|'timeZone']} onChange={e=>changeEvent(index,key,e.target.value)}/></label>)}<label>{t('Location or online meeting information','Lugar o información de la reunión virtual')}<input maxLength={500} value={eventText(item,'location')} onChange={e=>changeEvent(index,'location',e.target.value)}/></label><label>{t('Official registration URL','URL oficial de registro')}<input maxLength={2000} value={item.registrationUrl} onChange={e=>changeEvent(index,'registrationUrl',e.target.value)}/></label><button type="button" className="text-button" onClick={()=>onChange({...page,content:{...content,events:content.events.filter((_,n)=>n!==index)}})}>{t(`Remove event ${index+1}`,`Quitar evento ${index+1}`)}</button></fieldset>)}
 <button type="button" className="button outline" disabled={content.events.length>=30} onClick={()=>onChange({...page,content:{...content,events:[...content.events,{id:crypto.randomUUID(),title:'',description:'',startsAt:'',endsAt:'',timeZone:'America/Los_Angeles',location:'',registrationUrl:''}]}})}>{t('Add an event','Agregar evento')}</button>
 </div></>;
}
