import {useEffect,useState} from 'react';
type Member={auth0_subject:string;role:string;first_name:string;work_email:string};
type Invite={id:string;recipient_email:string;role:string;expires_at:string;accepted_at?:string;revoked_at?:string};
type Team={members?:Member[];invites?:Invite[];history?:{action:string;created_at:string}[]};
export default function InstitutionTeam({id,name,request,es,onChanged,onClose}:{id:string;name:string;request:(input:unknown)=>Promise<unknown>;es:boolean;onChanged:()=>void;onClose:()=>void}){
 const [team,setTeam]=useState<Team>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('editor'),[link,setLink]=useState(''),[notice,setNotice]=useState('');
 const t=(a:string,b:string)=>es?b:a;
 const roles=[['editor','Editor','Editor'],['outreach','Outreach staff','Personal de alcance'],['analyst','Analyst','Analista']];
 async function load(){setBusy(true);setError('');try{setTeam(await request({action:'team',id}) as Team);}catch{setError(t('Could not load the team. Try again.','No se pudo cargar el equipo. Intenta de nuevo.'));}finally{setBusy(false);}}
 useEffect(()=>{void load();},[id]);
 async function change(input:Record<string,unknown>){setBusy(true);setError('');setNotice('');setLink('');try{const data=await request({...input,id}) as {token?:string};if(data.token)setLink(`${window.location.origin}/#institution-invite/${data.token}`);if(input.action==='transfer-owner'){onChanged();onClose();return;}setTeam(await request({action:'team',id}) as Team);setNotice(t('Team updated.','Equipo actualizado.'));}catch(e){const code=e instanceof Error?e.message:'';setError(code==='reauthentication_required'?t('Sign in again using the review sign-in button before transferring ownership.','Inicia sesión de nuevo con el botón de revisión antes de transferir la propiedad.'):code==='transfer_ownership_first'?t('Transfer ownership before removing or changing an owner.','Transfiere la propiedad antes de quitar o cambiar a un propietario.'):t('Could not update the team. Check your access and try again.','No se pudo actualizar el equipo. Revisa tu acceso e intenta de nuevo.'));}finally{setBusy(false);}}
 return <section className="institution-editor" aria-label={t('Team management','Gestión del equipo')}><div className="institution-actions"><h2>{name} · {t('Team','Equipo')}</h2><button className="button outline" disabled={busy} onClick={onClose}>{t('Close team','Cerrar equipo')}</button><button className="text-button" disabled={busy} onClick={()=>void load()}>{t('Refresh team','Actualizar equipo')}</button></div><p>{t('Access applies only to this workspace. Editors manage drafts; outreach staff and analysts can view the workspace and its aggregate insights. Outreach tools will be added in a later phase.','El acceso corresponde solo a este espacio. Los editores gestionan borradores; el personal de alcance y los analistas pueden ver el espacio y sus estadísticas agregadas. Las herramientas de alcance se agregarán en otra fase.')}</p>
 <form onSubmit={e=>{e.preventDefault();void change({action:'invite',email,role});}}><fieldset disabled={busy}><legend>{t('Invite a coworker','Invita a un colega')}</legend><label>{t('Their sign-in email','Su correo de inicio de sesión')}<input required type="email" maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('Access','Acceso')}<select aria-label={t('Access','Acceso')} value={role} onChange={e=>setRole(e.target.value)}>{roles.map(([value,en,sp])=><option key={value} value={value}>{t(en,sp)}</option>)}</select></label><button className="button primary">{t('Create invitation link','Crear enlace de invitación')}</button></fieldset></form>
 <p className="small-text">{t('Share the link yourself with the intended coworker. It expires after seven days and requires that verified sign-in email. Creating a link does not send a message.','Comparte el enlace con el colega indicado. Vence en siete días y requiere ese correo verificado de inicio de sesión. Crear un enlace no envía un mensaje.')}</p>
 {link&&<label>{t('Invitation link','Enlace de invitación')}<input readOnly value={link} onFocus={e=>e.target.select()}/></label>}
 <h3>{t('Members','Miembros')}</h3>{team.members?.map(m=><div key={m.auth0_subject} className="institution-team-member"><div><strong>{m.first_name}</strong><p>{m.work_email} · {m.role}</p></div>{m.role!=='owner'&&<div className="institution-actions"><label>{t('Role','Rol')}<select aria-label={`${t('Role for','Rol de')} ${m.first_name}`} disabled={busy} value={m.role} onChange={e=>void change({action:'set-role',subject:m.auth0_subject,role:e.target.value})}>{roles.map(([value,en,sp])=><option key={value} value={value}>{t(en,sp)}</option>)}</select></label><button className="button outline" disabled={busy} onClick={()=>{if(window.confirm(t(`Remove ${m.first_name}'s access?`,`¿Quitar el acceso de ${m.first_name}?`)))void change({action:'remove-member',subject:m.auth0_subject});}}>{t('Remove','Quitar')}</button><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm(t(`Make ${m.first_name} the owner? You will become an editor.`,`¿Nombrar a ${m.first_name} como propietario? Pasarás a ser editor.`)))void change({action:'transfer-owner',subject:m.auth0_subject});}}>{t('Transfer ownership','Transferir propiedad')}</button></div>}</div>)}
 <h3>{t('Invitations','Invitaciones')}</h3>{team.invites?.map(inv=><div className="institution-team-member" key={inv.id}><p>{inv.recipient_email} · {inv.role} · {inv.accepted_at?t('Accepted','Aceptada'):inv.revoked_at?t('Revoked','Revocada'):new Date(inv.expires_at)<=new Date()?t('Expired','Vencida'):t('Pending','Pendiente')}</p>{!inv.accepted_at&&!inv.revoked_at&&new Date(inv.expires_at)>new Date()&&<button className="button outline" disabled={busy} onClick={()=>void change({action:'revoke-invite',inviteId:inv.id})}>{t('Revoke','Revocar')}</button>}</div>)}
 <details><summary>{t('Recent access changes','Cambios de acceso recientes')}</summary>{team.history?.map((event,index)=><p key={index}>{event.action} · {new Date(event.created_at).toLocaleString(es?'es':'en')}</p>)}</details>{busy&&<p role="status">{t('Updating team…','Actualizando equipo…')}</p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}</section>;
}
