import {useState} from 'react';
export function institutionShareURL(slug:string,es=false,eventId='',campaignId=''){
 const base=(import.meta.env.VITE_API_URL||window.location.origin).replace(/\/$/,'');const url=campaignId?new URL(`/institutions/${slug}`,window.location.origin):new URL(`${base}/api/institutions/pages/${slug}`);if(campaignId)url.searchParams.set('campaign',campaignId);if(es)url.searchParams.set('lang','es');if(eventId)url.searchParams.set('event',eventId);return url.href;
}
export default function InstitutionSharing({slug,es,eventId,campaignId}:{slug:string;es:boolean;eventId?:string;campaignId?:string}){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),t=(a:string,b:string)=>es?b:a,url=institutionShareURL(slug,es,eventId,campaignId);
 async function copy(){try{await navigator.clipboard.writeText(url);setStatus(t('Link copied.','Enlace copiado.'));}catch{setStatus(t('Copy the link from the field below.','Copia el enlace del campo de abajo.'));}}
 async function qr(){setBusy(true);setStatus('');try{const QRCode=await import('qrcode');const png=await QRCode.toDataURL(url,{width:640,margin:4,errorCorrectionLevel:'M',color:{dark:'#303841',light:'#FFFFFF'}});const a=document.createElement('a');a.href=png;a.download=`${slug}${eventId?'-event':''}-qr.png`;a.click();setStatus(t('QR code downloaded.','Código QR descargado.'));}catch{setStatus(t('Could not create the QR code. Please try again.','No se pudo crear el código QR. Intenta de nuevo.'));}finally{setBusy(false);}}
 return <div className="institution-sharing"><div className="institution-actions"><button className="button outline" onClick={()=>void copy()}>{t('Copy share link','Copiar enlace')}</button><button className="button outline" disabled={busy} onClick={()=>void qr()}>{busy?t('Creating QR…','Creando QR…'):t('Download QR','Descargar QR')}</button></div><label className="small-text">{campaignId?t('Campaign link','Enlace de campaña'):eventId?t('Approved event link','Enlace del evento aprobado'):t('Approved page link','Enlace de la página aprobada')}<input readOnly value={url} onFocus={e=>e.target.select()}/></label>{status&&<p role="status">{status}</p>}</div>;
}
