import {useEffect,useState} from 'react';
import {usePageLanguage} from './usePageLanguage';
import {safeInstitutionURL} from './institutionContent.mjs';
import './InstitutionPortal.css';
type Entry={slug:string;name:string;intro:string;logoUrl:string;spanishName:string;spanishIntro:string;unitType:string;parent?:{name:string;slug:string}};
export default function InstitutionDirectory(){
 const [es,setEs]=useState(localStorage.getItem('origen.language')==='es'),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[cursor,setCursor]=useState(''),[next,setNext]=useState<string|null>(null),[entries,setEntries]=useState<Entry[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0);const t=(a:string,b:string)=>es?b:a;usePageLanguage(es?'es':'en');
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError(false);const params=new URLSearchParams({q:query,cursor});void fetch(`${(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')}/api/institutions/directory?${params}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error();const data=await response.json();if(!controller.signal.aborted){setEntries(data.entries);setNext(data.nextCursor);}}).catch(()=>{if(!controller.signal.aborted)setError(true);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[query,cursor,retry]);
 return <main className="institution-shell institution-directory"><div className="institution-actions"><a className="institution-logo" href="/">○ origen.</a><button className="text-button" onClick={()=>setEs(!es)}>{es?'English':'Español'}</button><a href="/#institutions">{t('Register your institution','Registra tu institución')}</a></div><span className="institution-eyebrow">{t('EXPLORE YOUR NEXT STEP','EXPLORA TU SIGUIENTE PASO')}</span><h1>{t('Institutions and opportunities','Instituciones y oportunidades')}</h1><p>{t('Discover institution-provided information for starting college, transferring, learning as an adult, or supporting someone you care about. Confirm requirements on official websites.','Descubre información institucional para empezar la universidad, transferirte, aprender como adulto o apoyar a alguien. Confirma los requisitos en los sitios oficiales.')}</p><form className="institution-directory-search" onSubmit={e=>{e.preventDefault();setCursor('');setQuery(search.trim());setRetry(n=>n+1);}}><label>{t('Search institution or department name','Busca una institución o departamento')}<input maxLength={120} value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="button primary" disabled={busy}>{t('Search','Buscar')}</button></form>{busy?<p role="status">{t('Loading approved pages…','Cargando páginas aprobadas…')}</p>:error?<div role="alert"><p>{t('Could not load the directory. Please try again.','No se pudo cargar el directorio. Intenta de nuevo.')}</p><button className="button outline" onClick={()=>setRetry(n=>n+1)}>{t('Try again','Intentar de nuevo')}</button></div>:<><div className="institution-record-grid">{entries.map(entry=><article className="institution-draft-card" key={entry.slug}>{safeInstitutionURL(entry.logoUrl)&&<img className="institution-public-logo" src={entry.logoUrl} alt="" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.hidden=true;}}/>}<span className="institution-eyebrow">{entry.parent?entry.parent.name:t('Institution','Institución')}</span><h2>{es&&entry.spanishName||entry.name}</h2><p lang={es&&entry.spanishIntro?'es':'en'}>{es&&entry.spanishIntro||entry.intro}</p>{es&&!entry.spanishIntro&&entry.intro&&<p className="small-text">{t('Original-language introduction','Introducción en el idioma original')}</p>}<a className="button outline" href={`/institutions/${entry.slug}${es?'?lang=es':''}`}>{t('Explore this page','Explora esta página')} ↗</a></article>)}</div>{!entries.length&&<p>{t('No approved pages match this search yet.','Aún no hay páginas aprobadas que coincidan con la búsqueda.')}</p>}<div className="institution-actions">{cursor&&<button className="button outline" onClick={()=>setCursor('')}>{t('Back to first results','Volver a los primeros resultados')}</button>}{next&&<button className="button outline" onClick={()=>setCursor(next)}>{t('Next results','Siguientes resultados')}</button>}</div></>}</main>;
}
