const email=(import.meta.env.VITE_PUBLIC_CONTACT_EMAIL as string|undefined)||'daniel@origenedu.ai';
export const publicContactEmail=email&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:undefined;
type Props={t:(en:string,es:string)=>string;section?:'privacy'|'contact'};
export default function LandingDetails({t,section}:Props){
 const contact=publicContactEmail;
 return <>
  {section!=='contact'&&<section className="landing-resource" id="privacy" aria-labelledby="privacy-title">
   <span className="landing-eyebrow">{t('PRIVACY','PRIVACIDAD')}</span><h2 id="privacy-title">{t('Understand what you share.','Conoce lo que compartes.')}</h2>
   <p>{t('The public preview uses sample student profiles. Information you add in the preview may remain in this browser. Avoid entering sensitive personal information, especially on a shared device.','La vista previa pública usa perfiles de ejemplo. La información que agregues puede permanecer en este navegador. Evita ingresar información personal sensible, especialmente en un dispositivo compartido.')}</p>
   <p>{t('Signed-in features use account and student information to provide guidance and save records. When you ask an AI question, relevant profile information and conversation context are sent to OpenAI. Starting a voice conversation sends microphone audio to OpenAI; conversation summaries may be saved to your account.','Las funciones con sesión iniciada usan información de cuenta y del estudiante para ofrecer orientación y guardar registros. Cuando haces una pregunta a la IA, se envían a OpenAI la información pertinente del perfil y el contexto de la conversación. Al iniciar una conversación de voz, se envía el audio del micrófono a OpenAI; los resúmenes pueden guardarse en tu cuenta.')}</p>
   <p>{t('Sign-in is handled by Auth0. Hosting services process request and diagnostic information to operate the service. Provider processing and backups are separate from the records you see in Origen.','Auth0 gestiona el inicio de sesión. Los servicios de alojamiento procesan información de solicitudes y diagnóstico para operar el servicio. El procesamiento de proveedores y las copias de seguridad son distintos de los registros que ves en Origen.')}</p>
   <p>{t('When enabled for signed-in conversations, Origen keeps limited operational history: session times, topics, confirmed student references, language, connection events, model configuration references and official-source links. These records help diagnose problems and are deleted after 90 days, with scheduled cleanup running hourly. They do not include stored audio or a transcript. Saved summaries and profiles have a separate account lifecycle. Preview conversations are excluded from this history. This does not grant institutions access to family records or enroll anyone in research or model training.','Cuando está habilitado para conversaciones con sesión iniciada, Origen conserva un historial operativo limitado: fechas de sesiones, temas, referencias a estudiantes confirmados, idioma, eventos de conexión, referencias de configuración del modelo y enlaces oficiales. Estos registros ayudan a diagnosticar problemas y se eliminan después de 90 días, mediante una limpieza programada cada hora. No incluyen audio guardado ni una transcripción. Los resúmenes y perfiles tienen un ciclo de conservación separado. Las conversaciones de vista previa se excluyen de este historial. Esto no da a las instituciones acceso a los datos familiares ni inscribe a nadie en investigación o entrenamiento de modelos.')}</p>
   <p>{t('When progress history is enabled, accepted academic profile changes and plan revisions are kept privately for 90 days. Optional helpfulness feedback and progress you report are also kept for 90 days. Reported progress is not a verified school record, and feedback is not a learning score. Names and private profile notes are not copied into academic-change history. You can download retained records through account settings; deleting the relevant student or plan removes its history.','Cuando est� habilitado el historial de progreso, los cambios acad�micos aceptados del perfil y las versiones del plan se conservan de forma privada durante 90 d�as. Los comentarios opcionales y el progreso que reportas tambi�n se conservan durante 90 d�as. El progreso reportado no es un registro escolar verificado y los comentarios no son una calificaci�n del aprendizaje. Los nombres y las notas privadas del perfil no se copian al historial de cambios acad�micos. Puedes descargar los registros conservados desde la configuraci�n de la cuenta; eliminar el estudiante o plan correspondiente borra su historial.')}</p>
   <p>{t('Family linking is optional. Review what you share before linking accounts. Sharing Origen with a school or outreach team does not give that team access to your private profile or conversations.','Vincular cuentas familiares es opcional. Revisa lo que compartes antes de vincular cuentas. Compartir Origen con una escuela o equipo de orientación no da a ese equipo acceso a tu perfil o conversaciones privadas.')}</p>
   <p>{t('Signed-in account settings include data download and account closure controls. Closing an account does not erase downloaded files or copies on other devices; backups and sign-in-provider records are handled separately. Do not enter Social Security numbers, passwords, tax documents, or financial account numbers in guidance conversations.','La configuración de una cuenta con sesión iniciada incluye controles para descargar datos y cerrar la cuenta. Cerrar una cuenta no borra archivos descargados ni copias en otros dispositivos; las copias de seguridad y los registros del proveedor de acceso se gestionan por separado. No ingreses números de Seguro Social, contraseñas, documentos fiscales ni números de cuentas financieras en las conversaciones.')}</p>
  </section>}
  {section!=='privacy'&&contact&&<section className="landing-resource" id="contact" aria-labelledby="contact-title"><span className="landing-eyebrow">{t('CONTACT','CONTACTO')}</span><h2 id="contact-title">{t('Get in touch with Origen.','Contacta a Origen.')}</h2><p>{t('Origen Edu is operated by Blueprint Holdings LLC.','Origen Edu es operado por Blueprint Holdings LLC.')}</p><p>{t('Questions about Origen, sharing it with your community, or your information? Email us. Please keep student records and sensitive details out of your message.','¿Tienes preguntas sobre Origen, cómo compartirlo con tu comunidad o tu información? Escríbenos. No incluyas registros de estudiantes ni información sensible en tu mensaje.')}</p><a className="landing-share-link" href={`mailto:${contact}`}>{contact}</a></section>}
 </>;
}
