export default function LandingAbout({t}:{t:(en:string,es:string)=>string}){
 return (
   <section className="landing-resource" id="about" aria-labelledby="about-title">
    <span className="landing-eyebrow">{t('ABOUT ORIGEN','ACERCA DE ORIGEN')}</span>
    <h2 id="about-title">{t('A path forward, together.','Un camino adelante, juntos.')}</h2>
    <p>{t('Origen Edu is operated by Blueprint Holdings LLC.','Origen Edu es operado por Blueprint Holdings LLC.')}</p>
    <p>{t('Origen helps students and families understand college—from exploring their options and transfer pathways to navigating applications to making sense of financial aid and costs—with guidance in English and Spanish.','Origen ayuda a estudiantes y familias a entender la universidad: desde explorar sus opciones y caminos de transferencia hasta orientarse en las solicitudes hasta comprender la ayuda económica y los costos, con orientación en inglés y español.')}</p>
    <p>{t('Founded by a first-generation college graduate, Origen began with hands-on support for students navigating college admissions, including students who were accepted to UC Irvine and UC Riverside. That experience revealed a broader need: students and families benefit from continued guidance throughout the college-planning process.','Fundado por una persona graduada de la universidad de primera generación, Origen comenzó brindando apoyo directo a estudiantes durante el proceso de admisión universitaria, incluidos estudiantes que fueron aceptados en UC Irvine y UC Riverside. Esa experiencia reveló una necesidad más amplia: estudiantes y familias se benefician de una orientación continua durante todo el proceso de planificación universitaria.')}</p>
    <p>{t('Through financial-aid work and student outreach, we’ve seen how much information families receive—and how many questions remain after an event or conversation ends. For many English- and Spanish-speaking families, this is their first time navigating college, and a single conversation is only the beginning.','A través del trabajo en ayuda económica y orientación estudiantil, hemos visto cuánta información reciben las familias y cuántas preguntas quedan después de un evento o una conversación. Para muchas familias que hablan inglés o español, es la primera vez que se orientan en el proceso universitario, y una sola conversación es apenas el comienzo.')}</p>
    <p>{t('Origen grew from that work into a resource where students and families can continue guided research at their own pace. They can revisit explanations, explore official resources, and ask new questions as they learn.','Origen creció a partir de ese trabajo hasta convertirse en un recurso donde estudiantes y familias pueden continuar investigando con orientación y a su propio ritmo. Pueden volver a las explicaciones, explorar recursos oficiales y hacer nuevas preguntas mientras aprenden.')}</p>
    <p>{t('Our purpose is to help students and families stay informed, involved, and confident in their next steps, alongside the support available through schools, colleges, and student services.','Nuestro propósito es ayudar a estudiantes y familias a mantenerse informados, involucrados y seguros de sus próximos pasos, junto con el apoyo disponible en escuelas, universidades y servicios estudiantiles.')}</p>
   </section>
 );
}
