import {useEffect,useState} from 'react';
import {useAuth0} from '@auth0/auth0-react';
import {useFamily} from './FamilyStore';
import {linksRequest,inviteMessage,type LinkResult} from './linkClient';
import './LinkedAccounts.css';
export default function LinkedAccounts({t}:{t:(en:string,es:string)=>string}){
 const family=useFamily();const {getAccessTokenSilently}=useAuth0();
 const [data,setData]=useState<LinkResult>({links:[],invites:[]}),[studentId,setStudentId]=useState(family.students[0]?.id||''),[role,setRole]=useState<'parent'|'student'>('student'),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const request=(operation:Record<string,unknown>,signal?:AbortSignal)=>linksRequest(()=>getAccessTokenSilently(),import.meta.env.VITE_API_URL||'',operation,signal);
 useEffect(()=>{if(!family.cloud)return;const controller=new AbortController();setBusy(true);void request({action:'load'},controller.signal).then(setData).catch(()=>{if(!controller.signal.aborted)setMessage(t('Could not load linked accounts.','No se pudieron cargar las cuentas vinculadas.'));}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[family.cloud]);
 async function act(operation:Record<string,unknown>){
  if(busy)return;setBusy(true);setMessage('');
  try{const result=await request(operation);setData(result);if(result.token)setUrl(`${window.location.origin}/#invite/${result.token}`);if(operation.action==='revoke')setUrl('');if(operation.action==='unlink')family.reload();}
  catch(error){setMessage(inviteMessage(error,t('en','es')==='es'));}finally{setBusy(false);}
 }
 const owned=family.students.filter(s=>!data.links.some(l=>!l.isOwner&&l.studentId===s.id));
 return <section className="linked-accounts"><h3>{t('Linked accounts','Cuentas vinculadas')}</h3><p>{t('Support the same student, each with your own account. Shared profile fields can be edited by either person. Conversations, private notes and practical needs stay separate.','Apoyen al mismo estudiante con sus propias cuentas. Ambos pueden editar los campos compartidos del perfil. Las conversaciones, notas privadas y necesidades prácticas se mantienen separadas.')}</p>
 {!family.cloud?<p>{t('Sign in to invite a parent or student.','Inicia sesión para invitar a un padre o estudiante.')}</p>:<>
 {owned.length>0&&<div className="link-invite-form"><label>{t('Student profile','Perfil del estudiante')}<select value={owned.some(s=>s.id===studentId)?studentId:owned[0].id} onChange={e=>{setStudentId(e.target.value);setUrl('');}}>{owned.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>{t('Invite a','Invitar a')}<select value={role} onChange={e=>{setRole(e.target.value as 'parent'|'student');setUrl('');}}><option value="student">{t('Student','Estudiante')}</option><option value="parent">{t('Parent','Padre o madre')}</option></select></label><button className="button primary" disabled={busy} onClick={()=>void act({action:'create',studentId:owned.some(s=>s.id===studentId)?studentId:owned[0].id,role})}>{t('Create invitation link','Crear enlace de invitación')}</button></div>}
 {url&&<div className="generated-invite"><label>{t('Invitation link','Enlace de invitación')}<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className="link-actions"><button className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage(t('Link copied.','Enlace copiado.'));}catch{setMessage(t('Select and copy the link above.','Selecciona y copia el enlace de arriba.'));}}}>{t('Copy link','Copiar enlace')}</button>{!!navigator.share&&<button className="button outline" onClick={async()=>{try{await navigator.share({title:'Origen',text:t('Connect our accounts on Origen.','Vinculemos nuestras cuentas en Origen.'),url});}catch{/* Dismissing the share sheet does not revoke an invitation. */}}}>{t('Share','Compartir')}</button>}</div><small>{t('Send it by text, WhatsApp or email. Expires in 7 days and works once. Share only with the person you want to invite.','Envíalo por mensaje, WhatsApp o correo. Vence en 7 días y funciona una vez. Compártelo solo con la persona que quieres invitar.')}</small></div>}
 {data.links.map(link=><div className="linked-person" key={link.id}><div><strong>{link.personName||t('Linked family member','Familiar vinculado')}</strong><span>{link.studentName} · {link.isOwner?(link.role==='parent'?t('Parent','Padre o madre'):t('Student','Estudiante')):t('Profile owner','Creador del perfil')}</span></div><button className="text-button" disabled={busy} onClick={()=>{if(window.confirm(t('Unlink accounts? Future profile updates will stop syncing. Each person keeps their own profile copy and private history.','¿Desvincular cuentas? Los cambios futuros dejarán de sincronizarse. Cada persona conserva su copia del perfil y su historial privado.')))void act({action:'unlink',id:link.id});}}>{t('Unlink','Desvincular')}</button></div>)}
 {data.invites.map(invite=><div className="linked-person" key={invite.id}><div><strong>{invite.studentName}</strong><span>{t('Pending invitation','Invitación pendiente')} · {new Date(invite.expiresAt).toLocaleDateString()}</span></div><button className="text-button" disabled={busy} onClick={()=>void act({action:'revoke',id:invite.id})}>{t('Cancel invite','Cancelar invitación')}</button></div>)}
 {!data.links.length&&!data.invites.length&&!busy&&<small>{t('No linked accounts yet.','Aún no hay cuentas vinculadas.')}</small>}
 <button className="text-button" disabled={busy} onClick={()=>{void act({action:'load'});family.reload();}}>{t('Refresh linked accounts','Actualizar cuentas vinculadas')}</button>
 </>}{message&&<p role="status">{message}</p>}</section>;
}
