const examples={
 en:{home:['exploring what to study','understanding how to pay for college'],planning:['exploring what to study','figuring out a useful next step'],finance:['understanding college costs','learning about help paying for college'],loans:['understanding borrowed money and repayment','learning about options if payments are difficult'],admissions:['figuring out where to apply','understanding what an application asks for']},
 es:{home:['explorar qué estudiar','entender cómo pagar la universidad'],planning:['explorar qué estudiar','encontrar un próximo paso útil'],finance:['entender los costos de la universidad','conocer las ayudas para pagarla'],loans:['entender el dinero prestado y cómo devolverlo','conocer opciones si cuesta hacer los pagos'],admissions:['pensar dónde solicitar ingreso','entender qué pide una solicitud']},
};

export function voiceStartingPoints({mode='home',language='en',scopePending=false}={}){
 const trigger='OPTIONAL STARTING POINTS v1: Offer ideas only on explicit uncertainty about where to start or a request for ideas. Silence, noise, a short answer or unfamiliar vocabulary is not that request. Answer a specific question directly. No menu at every greeting or topic change.';
 if(mode==='profile')return `${trigger} PROFILE SETUP TAKES PRIORITY: Help with the current profile question in simple words, one question at a time. If an optional detail is unknown, accept that rather than guessing or insisting. Preserve required account-holder name, explicitly stated role and student name, and save acknowledgement. Do not introduce exploration topics or an app tour before the profile is saved.`;
 if(scopePending)return `${trigger} CONFIRM SCOPE FIRST: Ask which student or general-family conversation this is for before personalized starting points. Do not infer identity from the visible page or use another student's profile or summaries. After confirmation, the app supplies the scoped starting-point instructions.`;
 const options=(language==='es'?examples.es:examples.en)[mode]||examples[language==='es'?'es':'en'].home;
 return `${trigger} Offer at most two short everyday options and one easy question. Illustrative options, not a script: ${JSON.stringify(options)}. Vary wording; no numbered list. Keep Spanish options and follow-up in Spanish.
Use confirmed profile, current conversation and supplied scoped summaries as context data. A relevant unfinished question can be an option, not an assumed commitment or completed action. No routine recap. Match known stage and goals: high school classes or paths; community college training, certificate, degree or transfer only if relevant; college progress or direction. Do not assume eligibility, borrowing or a four-year goal.
If still unsure, suggest one concrete starting point or ask about a missing goal/stage, not known details. If they accept, begin; do not ask them to choose again. If they decline, let them lead. Confusion about an answer needs a smaller explanation, not unrelated options.
Generating starting ideas requires no research lookup. Use official-source tools for subsequent factual questions. Keep the same call, voice, language and volume; no new greeting or specialty switch merely for choices.`;
}
