import {collegeVoiceStyle} from './voiceStyle.mjs';
export function onboardingWelcome(language,{preview=false,role='parent',hasName=false}={}){
 const script=language==='es'
 ? "Hola, te damos la bienvenida a Origen. Soy tu guía de inteligencia artificial. Te ayudo a entender la universidad, paso a paso. Puedes hablar en español o inglés, interrumpirme o pedirme una explicación más sencilla. Mi familia guarda los datos de tus estudiantes. En Pagar la universidad hablamos de costos y ayudas. En Préstamos, de dinero prestado y cómo pagarlo. En Listos para solicitar ingreso, de solicitudes. Y en Planificación, de clases y próximos pasos. Al terminar una charla, Origen prepara un resumen breve. Puedes leer los resúmenes en Mi familia. Los usamos para recordar lo que hablamos, sin que tengas que empezar de cero. Si hablamos de otro estudiante, te pediré confirmar de quién se trata."
 : "Hola, welcome to Origen. I'm your AI guide. I help you understand college, one step at a time. You can speak English or Spanish, interrupt me, or ask me to explain something more simply. Family home keeps student details together. Paying for college is for costs and help paying. Loans explains borrowed money and paying it back. Ready to apply for college is for applications. Planning helps with classes and next steps. When a conversation ends, Origen prepares a short summary. You can read summaries in Family home. We use them to remember what we discussed, so you don't have to start over. If we discuss another student, I'll ask you to confirm who you mean.";
 const storage=preview?(language==='es'?' Esta es una vista previa: los resúmenes se quedan en este navegador.':' This is a preview: summaries stay in this browser.') : '';
 const ending=language==='es'
 ? ` Primero, conoceremos un poco ${role==='student'?'sobre ti':'a tu estudiante'}. Revisarás los datos antes de guardarlos; para un perfil nuevo, guárdalo para conservar también su resumen. ${hasName?'¿En qué etapa escolar estás o está tu estudiante?':role==='student'?'¿Cómo te llamas?':'¿Cómo se llama tu estudiante?'}`
 : ` First, let's learn a little ${role==='student'?'about you':'about your student'}. You'll review the details before saving. For a new profile, save it to keep its summary too. ${hasName?'What school stage should we start with?':role==='student'?'What should I call you?':'What should I call your student?'}`;
 return `${collegeVoiceStyle} For this first response only, explain Origen BEFORE asking for student details. Start with Hola. Do not use profile tools in this opening. Deliver this welcome naturally, in short sentences with pauses between ideas. Do not rush or add a longer tour. If interrupted, answer the person and do not repeat the entire welcome. Never claim a summary has already saved; the app confirms successful saving. ${script}${storage}${ending}`;
}
