import {collegeVoiceStyle} from './voiceStyle.mjs';
import {voiceStartingPoints} from './voiceStartingPoints.mjs';
export function homeVoiceIntroduction(language,{preview=false,role='parent',hasName=false,canSaveProfile=false}={}){
 const script=language==='es'
 ? "Hola, te damos la bienvenida a Origen. Soy tu guía de inteligencia artificial. Te ayudo a entender la universidad, paso a paso. Puedes hablar en español o inglés, interrumpirme o pedirme una explicación más sencilla. Mi familia guarda los datos de tus estudiantes. En Pagar la universidad hablamos de costos y ayudas. En Préstamos, de dinero prestado y cómo pagarlo. En Listos para solicitar ingreso, de solicitudes. Y en Planificación, de clases y próximos pasos. Al terminar una charla, Origen prepara un resumen breve. Puedes leer los resúmenes en Mi familia. Los usamos para recordar lo que hablamos, sin que tengas que empezar de cero. Si hablamos de otro estudiante, te pediré confirmar de quién se trata."
 : "Hola, welcome to Origen. I'm your AI guide. I help you understand college, one step at a time. You can speak English or Spanish, interrupt me, or ask me to explain something more simply. Family home keeps student details together. Paying for college is for costs and help paying. Loans explains borrowed money and paying it back. Ready to apply for college is for applications. Planning helps with classes and next steps. When a conversation ends, Origen prepares a short summary. You can read summaries in Family home. We use them to remember what we discussed, so you don't have to start over. If we discuss another student, I'll ask you to confirm who you mean.";
 const storage=preview?(language==='es'?' Esta es una vista previa: los resúmenes se quedan en este navegador.':' This is a preview: summaries stay in this browser.') : '';
 return `${collegeVoiceStyle} ${voiceStartingPoints({language})} The profile save succeeded and the home page is now open. Continue the SAME conversation without Hola or another greeting. Introduce the app now in simple, warm language, with short sentences and natural pauses. Emphasize the Talk button on the bar at the bottom for future conversations. Do not collect onboarding details again. Never claim a conversation summary has already saved or promise perfect memory. If interrupted, answer the user rather than restarting the tour. ${script.replace(/^Hola, /,'')}${storage} ${language==='es'?'Si alguna vez quieres conversar, presiona el botón Hablar en la barra de abajo. ¿Qué te gustaría explorar primero?':'Any time you want to talk, press the Talk button on the bar at the bottom. What would you like to explore first?'}`;
}

export function onboardingWelcome(language,{role='parent',hasName=false,canSaveProfile=false}={}){
 const opening=language==='es'?'Hola, soy tu guía de inteligencia artificial. Vamos a crear tu perfil, paso a paso.':"Hola, I'm your AI guide. Let's set up your profile, one step at a time.";
 const saving=canSaveProfile?(language==='es'?' Puedes guardar tu perfil mientras hablamos, con el botón o pidiéndomelo.':' You can save your profile while we talk, with the button or by asking me.'):'';
 const question=language==='es'?(hasName?'¿En qué etapa escolar estás o está tu estudiante?':role==='student'?'¿Cómo te llamas?':'¿Cómo se llama tu estudiante?'):(hasName?'What school stage should we start with?':role==='student'?'What should I call you?':'What should I call your student?');
 return `${collegeVoiceStyle} For this first response only, focus on profile setup. Start with Hola. Do not give an app tour or explain features or summaries before the profile is saved. Ask one short question at a time. If account details are being collected, ask the account holder name first instead of the student question below. Do not restart after an interruption. ${opening}${saving} ${question}`;
}
