import {onboardingRecovery,validOnboardingDraft} from './onboardingRecovery.mjs';
import {useAuth0} from '@auth0/auth0-react';
import {useEffect,useRef,useState} from 'react';
import './Welcome.css';
import ProfileVoice from './ProfileVoice';
import {type StudentProfile} from './planning';

export default function Welcome({language,setLanguage,complete,cloud=false,hasStudents=false,onRole,initialName="",initialRole}:{language:'en'|'es';setLanguage:(v:'en'|'es')=>void;cloud?:boolean;hasStudents?:boolean;onRole?:(role:'parent'|'student')=>void;initialName?:string;initialRole?:'parent'|'student';complete:(firstName:string,role:'parent'|'student',student?:StudentProfile)=>Promise<boolean>}){
 const t=(en:string,es:string)=>language==='es'?es:en;
 const {user}=useAuth0();
 const [recovery]=useState(()=>onboardingRecovery(localStorage,`origen.onboarding.${cloud?user?.sub:'preview'}.v1`));
 const [restored]=useState(()=>recovery.read<{name:string;step:'name'|'choice'|'voice'|'manual';role:'parent'|'student'|'';draft:StudentProfile}|null>(null,validOnboardingDraft));
 const [name,setName]=useState(restored?.name||initialName);
 const [step,setStep]=useState<'name'|'choice'|'voice'|'manual'>(restored?.step||'name');
 const [role,setRole]=useState<'parent'|'student'|''>(restored?.role||initialRole||'');
 const [storageError,setStorageError]=useState(false);
 const completed=useRef(false);
 const [active,setActive]=useState(false),[error,setError]=useState('');
 const [draft,setDraft]=useState<StudentProfile>(restored?.draft||{id:crypto.randomUUID(),name:'',stage:'',interest:'',gpa:'',color:'lilac'});
 const [saving,setSaving]=useState(false);
 const review=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(!completed.current)setStorageError(!recovery.write({name,step,role,draft}));},[name,step,role,draft,recovery]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(!completed.current&&(name.trim()||draft.name.trim()||active)){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[name,draft,active]);
 const finish=async(student?:StudentProfile)=>{if(saving||active||!role)return;setSaving(true);setError('');try{if(await complete(name.trim(),role,student)){completed.current=true;recovery.clear();onRole?.(role);}else setError(t('Could not save. Your details are still here. Please try again.','No se pudo guardar. Tus datos siguen aquí. Intenta de nuevo.'));}catch{setError(t('Could not save. Please try again.','No se pudo guardar. Intenta de nuevo.'));}finally{setSaving(false);}};
 if(step==='voice')return <main className="welcome-conversation">
  <header className="welcome-conversation-header"><a href="#" onClick={e=>e.preventDefault()} className="welcome-wordmark" aria-label="Origen">origen<span>.</span></a><button className="button outline" disabled={active||saving} onClick={()=>setLanguage(language==='en'?'es':'en')}>{language==='en'?'Español':'English'}</button></header>
  <section className="welcome-story" aria-labelledby="welcome-story-title"><p className="eyebrow">{t('A LITTLE ABOUT YOU','UN POCO SOBRE TI')}</p><h1 id="welcome-story-title">{t(`Let’s get to know you, ${name.trim()}.`,`Conozcámonos, ${name.trim()}.`)}</h1><p className="welcome-story-intro">{t('Just talk. Your profile takes shape here as you share. Nothing is saved to your profile until you choose Save profile.','Solo conversa. Tu perfil toma forma aquí mientras compartes. Nada se guarda en tu perfil hasta que elijas Guardar perfil.')}</p>
  <div className="welcome-live-notes" aria-label={t('Profile draft','Borrador del perfil')}>
   {!Object.entries(draft).some(([field,value])=>field!=='id'&&field!=='color'&&typeof value==='string'&&value.trim())&&<p className="welcome-empty-note">{role==='student'?t('Your story starts with whatever you’d like to share.','Tu historia empieza con lo que quieras compartir.'):t('Tell Origen a little about your student.','Cuéntale a Origen un poco sobre tu estudiante.')}</p>}
   {([['name','Name','Nombre'],['stage','Education stage','Etapa educativa'],['school','School or college','Escuela o colegio'],['interest','Interests','Intereses'],['goals','Goals','Metas'],['activities','Activities and responsibilities','Actividades y responsabilidades'],['institutions','Colleges of interest','Universidades de interés'],['entryTerm','Intended entry term','Período de ingreso'],['needs','Practical needs','Necesidades prácticas'],['notes','Notes','Notas'],['gpa','Reported GPA','GPA reportado']] as const).filter(([field])=>draft[field]?.trim()).map(([field,en,es])=><section className="welcome-live-note" key={field}><h2>{t(en,es)}</h2><p key={draft[field]}>{draft[field]?.split(/\s+/).map((word,index)=><span className="welcome-written-word" style={{animationDelay:`${Math.min(index*32,1100)}ms`}} key={index}>{word}{' '}</span>)}</p></section>)}
  </div><p className="welcome-draft-status" role="status">{active?t('Drafting your profile · You can correct a detail out loud.','Creando tu perfil · Puedes corregir un dato en voz alta.'):draft.name.trim()?t('Your draft is ready to review. You can edit details before saving.','Tu borrador está listo para revisar. Puedes editarlo antes de guardar.'):t('Start a conversation to bring your profile to life.','Inicia una conversación para darle vida a tu perfil.')}</p></section>
  <footer className="welcome-conversation-dock"><ProfileVoice onboarding recoveryKey={`origen.onboarding.voice.${cloud?user?.sub:'preview'}.${draft.id}`} profile={draft} language={language} role={role||'parent'} t={t} onActive={setActive} onDraft={changes=>setDraft(prev=>({...prev,...changes}))} apply={changes=>setDraft(prev=>({...prev,...changes}))}/>
   <div className="welcome-conversation-actions"><button className="text-button" disabled={active||saving} onClick={()=>setStep('manual')}>{t('Edit details','Editar datos')}</button><button className="button primary" disabled={active||saving||!draft.name.trim()} onClick={()=>void finish({...draft,name:draft.name.trim()})}>{saving?t('Saving…','Guardando…'):t('Save profile','Guardar perfil')}</button></div><p className="welcome-dock-hint">{active?t('End the conversation when you’re ready to save.','Termina la conversación cuando quieras guardar.'):!draft.name.trim()?t('Share a name to save, or choose Edit details.','Comparte un nombre para guardar o elige Editar datos.'):cloud?t('Save this profile to your account.','Guarda este perfil en tu cuenta.'):t('This preview saves in your browser.','Esta vista previa se guarda en tu navegador.')}</p>
   {storageError&&<p role="alert">{t('Your draft could not be backed up. Keep this page open until you save.','No se pudo conservar el borrador. Mantén esta página abierta hasta guardar.')}</p>}{error&&<p role="alert">{error}</p>}
  </footer></main>;
 return <main className={`application-panel welcome-panel${step==='manual'?' welcome-profile-step':''}`}>
 <button className="button outline" disabled={active||saving} onClick={()=>setLanguage(language==='en'?'es':'en')}>{language==='en'?'Español':'English'}</button>
 <p className="small-text muted">{t('Unfinished setup is kept on this device for up to 24 hours so you can return to it.','Los datos sin terminar se conservan en este dispositivo hasta 24 horas para que puedas volver.')}</p>
 <p className="eyebrow">{t('WELCOME TO ORIGEN','BIENVENIDO A ORIGEN')}</p>
 <h1>{step==='name'?t('What should we call you?','¿Cómo te llamas?'):t(`Welcome, ${name.trim()}.`,`Bienvenido, ${name.trim()}.`)}</h1>
 {step==='name'?<form onSubmit={e=>{e.preventDefault();if(name.trim()&&role)setStep('choice');}}><label className="field">{t('Your first name','Tu nombre')}<input required autoComplete="given-name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><fieldset className="welcome-role"><legend>{t('Who are you here for?','¿Para quién buscas ayuda?')}</legend><label><input type="radio" name="welcome-role" checked={role==='student'} onChange={()=>setRole('student')}/>{t('I am a student','Soy estudiante')}</label><label><input type="radio" name="welcome-role" checked={role==='parent'} onChange={()=>setRole('parent')}/>{t('I am a parent or guardian','Soy madre, padre o tutor')}</label></fieldset><button className="button primary" disabled={!name.trim()||!role||saving}>{t('Continue','Continuar')}</button></form>:<>
 <p>{t('Origen helps you understand college, paying for it, and your next steps. Ask in English or Spanish.','Origen te ayuda a entender la universidad, cómo pagarla y tus próximos pasos. Pregunta en español o inglés.')}</p>
 <button type="button" className="text-button" disabled={active||saving} onClick={()=>setStep('name')}>{t('Edit my name or role','Editar mi nombre o rol')}</button>
 <h2>{role==='student'?t('Tell us about yourself','Cuéntanos sobre ti'):t('Tell us about your student','Cuéntanos sobre tu estudiante')}</h2>
 {step==='choice'?<><div className="welcome-tour"><p>{t('Family home keeps student details and conversation summaries together. Origen uses those summaries to help you pick up where you left off.','Mi familia reúne los datos y resúmenes de conversaciones. Origen usa esos resúmenes para retomar lo que hablaron.')}</p><p>{t('Paying for college explains costs and financial help. Loans covers borrowing and repayment. Applications helps with forms and deadlines. Planning helps you choose classes and next steps.','Pagar la universidad explica costos y ayudas. Préstamos trata de dinero prestado y pagos. Solicitudes ayuda con formularios y fechas. Planificación ayuda con clases y próximos pasos.')}</p></div><p>{t('Talk naturally with Origen, or type what you know. You will review everything before saving.','Conversa naturalmente con Origen o escribe lo que sabes. Revisarás todo antes de guardar.')}</p><div className="card-actions"><button className="button primary" onClick={()=>setStep('voice')}>{t('Talk with Origen','Hablar con Origen')}</button><button className="button outline" onClick={()=>setStep('manual')}>{t('Enter details myself','Ingresar los datos')}</button></div><button className="text-button" disabled={saving} onClick={()=>void finish()}>{hasStudents?t('Continue to my family','Continuar a Mi familia'):role==='student'?t('Add my details later','Agregar mis datos después'):t('Add a student later','Agregar un estudiante después')}</button></>:<>
 {(step==='manual')&&<div className={step==='manual'?'welcome-voice-review-only':''}><ProfileVoice onboarding recoveryKey={`origen.onboarding.voice.${cloud?user?.sub:'preview'}.${draft.id}`}  profile={draft} language={language} role={role||'parent'} t={t} onActive={setActive} onDraft={changes=>setDraft(prev=>({...prev,...changes}))} apply={changes=>{setDraft(prev=>({...prev,...changes}));requestAnimationFrame(()=>review.current?.scrollIntoView({block:'start',behavior:'smooth'}));}}/></div>}
 <p className="small-text muted">{t('After a voice conversation, a short summary helps Origen remember what you discussed. Find it in Family home after saving the new student profile.','Después de una charla, un resumen breve ayuda a Origen a recordar lo conversado. Lo encontrarás en Mi familia al guardar el perfil nuevo.')}</p>
 <h3 ref={review} className="welcome-review-heading">{role==='student'?t('Review your profile','Revisa tu perfil'):t('Review your student’s profile','Revisa el perfil de tu estudiante')}</h3>
 <p>{t('Leave anything you don’t know blank. Your student details are saved when you choose Save profile.','Deja en blanco lo que no sabes. Los datos del estudiante se guardan cuando seleccionas Guardar perfil.')}</p>
 <fieldset disabled={active||saving} style={{border:0,padding:0}}><form id="welcome-profile-form" onSubmit={e=>{e.preventDefault();if(!active&&draft.name.trim())finish({...draft,name:draft.name.trim()});}}>
 <label className="field">{role==='student'?t('Your name','Tu nombre'):t('Student name','Nombre del estudiante')}<input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
 <label className="field">{t('Education stage','Etapa educativa')}<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}><option value="">{t('Not sure yet','No lo sé todavía')}</option>{['9th grade','10th grade','11th grade','12th grade','Community college','College'].map(s=><option key={s} value={s}>{t(s,s==='Community college'?'Colegio comunitario':s==='College'?'Universidad':`${s.match(/\d+/)?.[0]}.º grado`)}</option>)}</select></label>
 {([['interest','Interests','Intereses'],['activities','Activities and responsibilities','Actividades y responsabilidades'],['goals','Goals','Metas'],['school','School or college','Escuela o colegio'],['institutions','Colleges of interest','Universidades de interés'],['entryTerm','Intended entry term','Período de ingreso'],['needs','Practical needs','Necesidades prácticas'],['notes','Notes and who shared them','Notas y quién las compartió'],['gpa','Reported GPA (optional)','GPA reportado (opcional)']] as const).map(([field,en,es])=><label className="field" key={field}>{t(en,es)}<textarea maxLength={field==='gpa'?30:2000} value={draft[field]||''} onChange={e=>setDraft({...draft,[field]:e.target.value})}/></label>)}
 <p className="small-text muted">{cloud?t('Saved to your account after you confirm.','Se guarda en tu cuenta después de confirmar.'):t('Saved on this device’s browser.','Se guarda en el navegador de este dispositivo.')}</p>
 <div className="card-actions"><button type="button" className="button outline" disabled={active||saving} onClick={()=>setStep('voice')}>{t('Use voice instead','Usar voz')}</button></div>
 </form></fieldset><div className="welcome-save-bar"><p className="small-text" role="status">{active?t('End the conversation to review and save.','Termina la conversación para revisar y guardar.'):!draft.name.trim()?t('Add voice suggestions to the form or enter a student name to save.','Agrega las sugerencias al formulario o escribe el nombre del estudiante para guardar.'):t('Review the profile before saving.','Revisa el perfil antes de guardar.')}</p><button type="submit" form="welcome-profile-form" className="button primary" disabled={active||saving||!draft.name.trim()}>{saving?t('Saving…','Guardando…'):t('Save profile','Guardar perfil')}</button></div></> }</>}
 {storageError&&<p role="alert">{t('This browser could not keep your draft. Keep this page open until you save.','Este navegador no pudo conservar el borrador. Mantén esta página abierta hasta guardar.')}</p>}
 {restored&&<p className="small-text">{t('Your unfinished setup was restored on this device.','Se recuperaron tus datos sin terminar en este dispositivo.')}</p>}
 {error&&<p role="alert">{error}</p>}
 </main>;
}
